# coding: utf-8

"""
    Victory Code Client API

    Client APIs for Tactix partners: authenticate, upload game video, and retrieve games, plays, game recaps and team metadata.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from victorycode_sdk.models.rushing_dto import RushingDto

class TestRushingDto(unittest.TestCase):
    """RushingDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RushingDto:
        """Test RushingDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RushingDto`
        """
        model = RushingDto()
        if include_optional:
            return RushingDto(
                total_yards = 1.337,
                attempts = 1.337,
                yards_per_rush = 1.337
            )
        else:
            return RushingDto(
                total_yards = 1.337,
                attempts = 1.337,
                yards_per_rush = 1.337,
        )
        """

    def testRushingDto(self):
        """Test RushingDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
