# coding: utf-8

"""
    Victory Code Client API

    This collection provides the core set of APIs for Tactix clients to interact with the platform. It covers authentication and token management, as well as a wide range of game-related endpoints including uploading full games, fetching generated clips, checking clipping status, retrieving game scoring summaries, and accessing detailed team statistics. All requests are versioned to ensure backward compatibility and smooth upgrades.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from victorycode_sdk.api.game_recap_api import GameRecapApi


class TestGameRecapApi(unittest.TestCase):
    """GameRecapApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GameRecapApi()

    def tearDown(self) -> None:
        pass

    def test_get_game_recap_score(self) -> None:
        """Test case for get_game_recap_score

        Get the Game Recap Score for a specific Game
        """
        pass

    def test_get_game_recap_scoring_summary(self) -> None:
        """Test case for get_game_recap_scoring_summary

        Get the Game Recap Scoring Summary for a specific Game.
        """
        pass

    def test_get_game_recap_team_stats(self) -> None:
        """Test case for get_game_recap_team_stats

        Get the Game Recap Team Stats for a specific Game.
        """
        pass


if __name__ == '__main__':
    unittest.main()
