# coding: utf-8

"""
    Victory Code Client API

    Client APIs for Tactix partners: authenticate, upload game video, and retrieve games, plays, game recaps and team metadata.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from victorycode_sdk.models.conflict_error_response_dto import ConflictErrorResponseDto

class TestConflictErrorResponseDto(unittest.TestCase):
    """ConflictErrorResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConflictErrorResponseDto:
        """Test ConflictErrorResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConflictErrorResponseDto`
        """
        model = ConflictErrorResponseDto()
        if include_optional:
            return ConflictErrorResponseDto(
                code = 409,
                message = 'Resource already exists'
            )
        else:
            return ConflictErrorResponseDto(
                code = 409,
                message = 'Resource already exists',
        )
        """

    def testConflictErrorResponseDto(self):
        """Test ConflictErrorResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
