# coding: utf-8

"""
    Victory Code Client API

    Client APIs for Tactix partners: authenticate, upload game video, and retrieve games, plays, game recaps and team metadata.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from victorycode_sdk.models.single_classification_response_dto import SingleClassificationResponseDto

class TestSingleClassificationResponseDto(unittest.TestCase):
    """SingleClassificationResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SingleClassificationResponseDto:
        """Test SingleClassificationResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SingleClassificationResponseDto`
        """
        model = SingleClassificationResponseDto()
        if include_optional:
            return SingleClassificationResponseDto(
                message = 'Operation successful',
                data = victorycode_sdk.models.classification.Classification(
                    _id = '69b13dc5172b65400e926b31', 
                    name = 'GRANT_CLS_315', )
            )
        else:
            return SingleClassificationResponseDto(
                message = 'Operation successful',
                data = victorycode_sdk.models.classification.Classification(
                    _id = '69b13dc5172b65400e926b31', 
                    name = 'GRANT_CLS_315', ),
        )
        """

    def testSingleClassificationResponseDto(self):
        """Test SingleClassificationResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
