# coding: utf-8

"""
    Victory Code Client API

    Client APIs for Tactix partners: authenticate, upload game video, and retrieve games, plays, game recaps and team metadata.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from victorycode_sdk.api.mascot_api import MascotApi


class TestMascotApi(unittest.TestCase):
    """MascotApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MascotApi()

    def tearDown(self) -> None:
        pass

    def test_create_mascot(self) -> None:
        """Test case for create_mascot

        Create a new mascot
        """
        pass

    def test_delete_mascot(self) -> None:
        """Test case for delete_mascot

        Delete a mascot
        """
        pass

    def test_get_mascots(self) -> None:
        """Test case for get_mascots

        Get all mascots
        """
        pass

    def test_update_mascot(self) -> None:
        """Test case for update_mascot

        Update a mascot
        """
        pass


if __name__ == '__main__':
    unittest.main()
