# coding: utf-8

"""
    Victory Code Client API

    Client APIs for Tactix partners: authenticate, upload game video, and retrieve games, plays, game recaps and team metadata.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from victorycode_sdk.models.red_zone_dto import RedZoneDto

class TestRedZoneDto(unittest.TestCase):
    """RedZoneDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RedZoneDto:
        """Test RedZoneDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RedZoneDto`
        """
        model = RedZoneDto()
        if include_optional:
            return RedZoneDto(
                scores = 1.337,
                attempts = 1.337
            )
        else:
            return RedZoneDto(
                scores = 1.337,
                attempts = 1.337,
        )
        """

    def testRedZoneDto(self):
        """Test RedZoneDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
