# coding: utf-8

"""
    Victory Code Client API

    Client APIs for Tactix partners: authenticate, upload game video, and retrieve games, plays, game recaps and team metadata.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from victorycode_sdk.models.list_team_paginated_response_dto import ListTeamPaginatedResponseDto

class TestListTeamPaginatedResponseDto(unittest.TestCase):
    """ListTeamPaginatedResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListTeamPaginatedResponseDto:
        """Test ListTeamPaginatedResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListTeamPaginatedResponseDto`
        """
        model = ListTeamPaginatedResponseDto()
        if include_optional:
            return ListTeamPaginatedResponseDto(
                total = 150,
                limit = 20,
                offset = 100,
                data = [
                    victorycode_sdk.models.fetch_team_response_dto.FetchTeamResponseDto(
                        _id = '69c0bf178817c85a7d11b716', 
                        name = 'JAK', 
                        short_name = 'JA', 
                        sport = 'FOOTBALL', 
                        city = 'Kathmandu', 
                        state = 'Alaska', 
                        mascots = {"_id":"69bce3618817c85a7d1118f2","name":"ra"}, 
                        classification = [{"_id":"69b13dc5172b65400e926b31","name":"GRANT_CLS_315"}], 
                        created_at = '2026-03-23T04:18:31.588Z', 
                        updated_at = '2026-03-23T04:18:31.588Z', )
                    ]
            )
        else:
            return ListTeamPaginatedResponseDto(
                total = 150,
                limit = 20,
                offset = 100,
                data = [
                    victorycode_sdk.models.fetch_team_response_dto.FetchTeamResponseDto(
                        _id = '69c0bf178817c85a7d11b716', 
                        name = 'JAK', 
                        short_name = 'JA', 
                        sport = 'FOOTBALL', 
                        city = 'Kathmandu', 
                        state = 'Alaska', 
                        mascots = {"_id":"69bce3618817c85a7d1118f2","name":"ra"}, 
                        classification = [{"_id":"69b13dc5172b65400e926b31","name":"GRANT_CLS_315"}], 
                        created_at = '2026-03-23T04:18:31.588Z', 
                        updated_at = '2026-03-23T04:18:31.588Z', )
                    ],
        )
        """

    def testListTeamPaginatedResponseDto(self):
        """Test ListTeamPaginatedResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
