/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.victorycode.sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.victorycode.sdk.apis.UploadsApi
import ai.victorycode.sdk.models.BadRequestErrorResponseDto
import ai.victorycode.sdk.models.CompleteMultipartUploadDto
import ai.victorycode.sdk.models.CompleteMultipartUploadResponseDto
import ai.victorycode.sdk.models.GetPartsPresignUrlResponseDto
import ai.victorycode.sdk.models.InitiateMultipartUploadDto
import ai.victorycode.sdk.models.InitiateMultipartUploadResponseDto

class UploadsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UploadsApi
        //val apiInstance = UploadsApi()

        // to test completeMultipartUpload
        should("test completeMultipartUpload") {
            // uncomment below to test completeMultipartUpload
            //val completeMultipartUploadDto : CompleteMultipartUploadDto =  // CompleteMultipartUploadDto | 
            //val result : CompleteMultipartUploadResponseDto = apiInstance.completeMultipartUpload(completeMultipartUploadDto)
            //result shouldBe ("TODO")
        }

        // to test getPresignedUrl
        should("test getPresignedUrl") {
            // uncomment below to test getPresignedUrl
            //val uploadId : kotlin.String = uploadId_example // kotlin.String | 
            //val partNumber : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 
            //val result : GetPartsPresignUrlResponseDto = apiInstance.getPresignedUrl(uploadId, partNumber)
            //result shouldBe ("TODO")
        }

        // to test initiateUpload
        should("test initiateUpload") {
            // uncomment below to test initiateUpload
            //val initiateMultipartUploadDto : InitiateMultipartUploadDto =  // InitiateMultipartUploadDto | 
            //val result : InitiateMultipartUploadResponseDto = apiInstance.initiateUpload(initiateMultipartUploadDto)
            //result shouldBe ("TODO")
        }

    }
}
