# coding: utf-8

"""
    Victory Code Client API

    Client APIs for Tactix partners: authenticate, upload game video, and retrieve games, plays, game recaps and team metadata.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from victorycode_sdk.models.team_basic_info_dto import TeamBasicInfoDto
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GameDetailsResponse(BaseModel):
    """
    GameDetailsResponse
    """ # noqa: E501
    game_name: StrictStr = Field(alias="gameName", json_schema_extra={"examples": ["Final Game"]})
    date_time: datetime = Field(alias="dateTime", json_schema_extra={"examples": ["2026-03-10T10:30:00Z"]})
    game_id: StrictStr = Field(alias="gameId", json_schema_extra={"examples": ["game-id"]})
    source_id: StrictStr = Field(alias="sourceId", json_schema_extra={"examples": ["Game#20260310"]})
    venue: StrictStr = Field(json_schema_extra={"examples": ["Revolutionary Field"]})
    home_team: TeamBasicInfoDto = Field(alias="homeTeam")
    away_team: TeamBasicInfoDto = Field(alias="awayTeam")
    __properties: ClassVar[List[str]] = ["gameName", "dateTime", "gameId", "sourceId", "venue", "homeTeam", "awayTeam"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GameDetailsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of home_team
        if self.home_team:
            _dict['homeTeam'] = self.home_team.to_dict()
        # override the default output from pydantic by calling `to_dict()` of away_team
        if self.away_team:
            _dict['awayTeam'] = self.away_team.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GameDetailsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "gameName": obj.get("gameName"),
            "dateTime": obj.get("dateTime"),
            "gameId": obj.get("gameId"),
            "sourceId": obj.get("sourceId"),
            "venue": obj.get("venue"),
            "homeTeam": TeamBasicInfoDto.from_dict(obj["homeTeam"]) if obj.get("homeTeam") is not None else None,
            "awayTeam": TeamBasicInfoDto.from_dict(obj["awayTeam"]) if obj.get("awayTeam") is not None else None
        })
        return _obj


