# coding: utf-8

"""
    Victory Code Client API

    This collection provides the core set of APIs for Tactix clients to interact with the platform. It covers authentication and token management, as well as a wide range of game-related endpoints including uploading full games, fetching generated clips, checking clipping status, retrieving game scoring summaries, and accessing detailed team statistics. All requests are versioned to ensure backward compatibility and smooth upgrades.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from victorycode_sdk.models.get_game_response_data_home_team import GetGameResponseDataHomeTeam
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GetGameResponseData(BaseModel):
    """
    GetGameResponseData
    """ # noqa: E501
    game_name: Optional[StrictStr] = Field(default=None, alias="gameName")
    date_time: Optional[datetime] = Field(default=None, alias="dateTime")
    game_id: Optional[StrictStr] = Field(default=None, alias="gameId")
    location: Optional[StrictStr] = None
    venue: Optional[StrictStr] = None
    home_team: Optional[GetGameResponseDataHomeTeam] = Field(default=None, alias="homeTeam")
    away_team: Optional[GetGameResponseDataHomeTeam] = Field(default=None, alias="awayTeam")
    __properties: ClassVar[List[str]] = ["gameName", "dateTime", "gameId", "location", "venue", "homeTeam", "awayTeam"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetGameResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of home_team
        if self.home_team:
            _dict['homeTeam'] = self.home_team.to_dict()
        # override the default output from pydantic by calling `to_dict()` of away_team
        if self.away_team:
            _dict['awayTeam'] = self.away_team.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetGameResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "gameName": obj.get("gameName"),
            "dateTime": obj.get("dateTime"),
            "gameId": obj.get("gameId"),
            "location": obj.get("location"),
            "venue": obj.get("venue"),
            "homeTeam": GetGameResponseDataHomeTeam.from_dict(obj["homeTeam"]) if obj.get("homeTeam") is not None else None,
            "awayTeam": GetGameResponseDataHomeTeam.from_dict(obj["awayTeam"]) if obj.get("awayTeam") is not None else None
        })
        return _obj


