# coding: utf-8

"""
    Victory Code Client API

    This collection provides the core set of APIs for Tactix clients to interact with the platform. It covers authentication and token management, as well as a wide range of game-related endpoints including uploading full games, fetching generated clips, checking clipping status, retrieving game scoring summaries, and accessing detailed team statistics. All requests are versioned to ensure backward compatibility and smooth upgrades.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from victorycode_sdk.models.get_game_recap_score_response_data_home_team_period_scores_inner import GetGameRecapScoreResponseDataHomeTeamPeriodScoresInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GetGameRecapScoreResponseDataHomeTeam(BaseModel):
    """
    GetGameRecapScoreResponseDataHomeTeam
    """ # noqa: E501
    team_id: Optional[StrictStr] = Field(default=None, alias="teamId")
    source_id: Optional[StrictStr] = Field(default=None, alias="sourceId")
    name: Optional[StrictStr] = None
    short_name: Optional[StrictStr] = Field(default=None, alias="shortName")
    mascot: Optional[StrictStr] = None
    classification: Optional[StrictStr] = None
    total_score: Optional[StrictInt] = Field(default=None, alias="totalScore")
    period_scores: Optional[List[GetGameRecapScoreResponseDataHomeTeamPeriodScoresInner]] = Field(default=None, alias="periodScores")
    __properties: ClassVar[List[str]] = ["teamId", "sourceId", "name", "shortName", "mascot", "classification", "totalScore", "periodScores"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetGameRecapScoreResponseDataHomeTeam from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in period_scores (list)
        _items = []
        if self.period_scores:
            for _item_period_scores in self.period_scores:
                _items.append(_item_period_scores.to_dict() if _item_period_scores is not None else None)
            _dict['periodScores'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetGameRecapScoreResponseDataHomeTeam from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "teamId": obj.get("teamId"),
            "sourceId": obj.get("sourceId"),
            "name": obj.get("name"),
            "shortName": obj.get("shortName"),
            "mascot": obj.get("mascot"),
            "classification": obj.get("classification"),
            "totalScore": obj.get("totalScore"),
            "periodScores": [GetGameRecapScoreResponseDataHomeTeamPeriodScoresInner.from_dict(_item) for _item in obj["periodScores"]] if obj.get("periodScores") is not None else None
        })
        return _obj


