# coding: utf-8

"""
    Victory Code Client API

    Client APIs for Tactix partners: authenticate, upload game video, and retrieve games, plays, game recaps and team metadata.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class KickingTotalsDto(BaseModel):
    """
    KickingTotalsDto
    """ # noqa: E501
    field_goals_attempted: Union[StrictFloat, StrictInt] = Field(description="FG attempts", alias="fieldGoalsAttempted", json_schema_extra={"examples": [1]})
    field_goals_made: Union[StrictFloat, StrictInt] = Field(description="FG made", alias="fieldGoalsMade", json_schema_extra={"examples": [1]})
    field_goal_pct: Union[StrictFloat, StrictInt] = Field(description="PCT — (made / attempted) × 100", alias="fieldGoalPct", json_schema_extra={"examples": [100]})
    long_field_goal: Union[StrictFloat, StrictInt] = Field(description="LONG — longest made field goal in yards", alias="longFieldGoal", json_schema_extra={"examples": [45]})
    extra_points_attempted: Union[StrictFloat, StrictInt] = Field(description="XP attempts", alias="extraPointsAttempted", json_schema_extra={"examples": [1]})
    extra_points_made: Union[StrictFloat, StrictInt] = Field(description="XP made", alias="extraPointsMade", json_schema_extra={"examples": [1]})
    total_points: Union[StrictFloat, StrictInt] = Field(description="PTS — (FGM×3) + (XPM×1) + (2PC×2)", alias="totalPoints", json_schema_extra={"examples": [4]})
    __properties: ClassVar[List[str]] = ["fieldGoalsAttempted", "fieldGoalsMade", "fieldGoalPct", "longFieldGoal", "extraPointsAttempted", "extraPointsMade", "totalPoints"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of KickingTotalsDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of KickingTotalsDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "fieldGoalsAttempted": obj.get("fieldGoalsAttempted"),
            "fieldGoalsMade": obj.get("fieldGoalsMade"),
            "fieldGoalPct": obj.get("fieldGoalPct"),
            "longFieldGoal": obj.get("longFieldGoal"),
            "extraPointsAttempted": obj.get("extraPointsAttempted"),
            "extraPointsMade": obj.get("extraPointsMade"),
            "totalPoints": obj.get("totalPoints")
        })
        return _obj


