<?php
/**
 * GameBoxScoreMetaDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  VictoryCode\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Victory Code Client API
 *
 * Client APIs for Tactix partners: authenticate, upload game video, and retrieve games, plays, game recaps and team metadata.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace VictoryCode\SDK\Model;

use \ArrayAccess;
use \VictoryCode\SDK\ObjectSerializer;

/**
 * GameBoxScoreMetaDto Class Doc Comment
 *
 * @category Class
 * @package  VictoryCode\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GameBoxScoreMetaDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'GameBoxScoreMetaDto';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'game_id' => 'string',
        'game_title' => 'string',
        'video_id' => 'string',
        'view_type' => 'string',
        'home_team' => 'string',
        'away_team' => 'string',
        'home_score' => 'float',
        'away_score' => 'float',
        'generated_at' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'game_id' => null,
        'game_title' => null,
        'video_id' => null,
        'view_type' => null,
        'home_team' => null,
        'away_team' => null,
        'home_score' => null,
        'away_score' => null,
        'generated_at' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'game_id' => false,
        'game_title' => false,
        'video_id' => false,
        'view_type' => false,
        'home_team' => false,
        'away_team' => false,
        'home_score' => false,
        'away_score' => false,
        'generated_at' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'game_id' => 'gameId',
        'game_title' => 'gameTitle',
        'video_id' => 'videoId',
        'view_type' => 'viewType',
        'home_team' => 'homeTeam',
        'away_team' => 'awayTeam',
        'home_score' => 'homeScore',
        'away_score' => 'awayScore',
        'generated_at' => 'generatedAt'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'game_id' => 'setGameId',
        'game_title' => 'setGameTitle',
        'video_id' => 'setVideoId',
        'view_type' => 'setViewType',
        'home_team' => 'setHomeTeam',
        'away_team' => 'setAwayTeam',
        'home_score' => 'setHomeScore',
        'away_score' => 'setAwayScore',
        'generated_at' => 'setGeneratedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'game_id' => 'getGameId',
        'game_title' => 'getGameTitle',
        'video_id' => 'getVideoId',
        'view_type' => 'getViewType',
        'home_team' => 'getHomeTeam',
        'away_team' => 'getAwayTeam',
        'home_score' => 'getHomeScore',
        'away_score' => 'getAwayScore',
        'generated_at' => 'getGeneratedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('game_id', $data ?? [], null);
        $this->setIfExists('game_title', $data ?? [], null);
        $this->setIfExists('video_id', $data ?? [], null);
        $this->setIfExists('view_type', $data ?? [], null);
        $this->setIfExists('home_team', $data ?? [], null);
        $this->setIfExists('away_team', $data ?? [], null);
        $this->setIfExists('home_score', $data ?? [], null);
        $this->setIfExists('away_score', $data ?? [], null);
        $this->setIfExists('generated_at', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['game_id'] === null) {
            $invalidProperties[] = "'game_id' can't be null";
        }
        if ($this->container['game_title'] === null) {
            $invalidProperties[] = "'game_title' can't be null";
        }
        if ($this->container['video_id'] === null) {
            $invalidProperties[] = "'video_id' can't be null";
        }
        if ($this->container['view_type'] === null) {
            $invalidProperties[] = "'view_type' can't be null";
        }
        if ($this->container['home_team'] === null) {
            $invalidProperties[] = "'home_team' can't be null";
        }
        if ($this->container['away_team'] === null) {
            $invalidProperties[] = "'away_team' can't be null";
        }
        if ($this->container['home_score'] === null) {
            $invalidProperties[] = "'home_score' can't be null";
        }
        if ($this->container['away_score'] === null) {
            $invalidProperties[] = "'away_score' can't be null";
        }
        if ($this->container['generated_at'] === null) {
            $invalidProperties[] = "'generated_at' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets game_id
     *
     * @return string
     */
    public function getGameId()
    {
        return $this->container['game_id'];
    }

    /**
     * Sets game_id
     *
     * @param string $game_id game_id
     *
     * @return self
     */
    public function setGameId($game_id)
    {
        if (is_null($game_id)) {
            throw new \InvalidArgumentException('non-nullable game_id cannot be null');
        }
        $this->container['game_id'] = $game_id;

        return $this;
    }

    /**
     * Gets game_title
     *
     * @return string
     */
    public function getGameTitle()
    {
        return $this->container['game_title'];
    }

    /**
     * Sets game_title
     *
     * @param string $game_title game_title
     *
     * @return self
     */
    public function setGameTitle($game_title)
    {
        if (is_null($game_title)) {
            throw new \InvalidArgumentException('non-nullable game_title cannot be null');
        }
        $this->container['game_title'] = $game_title;

        return $this;
    }

    /**
     * Gets video_id
     *
     * @return string
     */
    public function getVideoId()
    {
        return $this->container['video_id'];
    }

    /**
     * Sets video_id
     *
     * @param string $video_id video_id
     *
     * @return self
     */
    public function setVideoId($video_id)
    {
        if (is_null($video_id)) {
            throw new \InvalidArgumentException('non-nullable video_id cannot be null');
        }
        $this->container['video_id'] = $video_id;

        return $this;
    }

    /**
     * Gets view_type
     *
     * @return string
     */
    public function getViewType()
    {
        return $this->container['view_type'];
    }

    /**
     * Sets view_type
     *
     * @param string $view_type view_type
     *
     * @return self
     */
    public function setViewType($view_type)
    {
        if (is_null($view_type)) {
            throw new \InvalidArgumentException('non-nullable view_type cannot be null');
        }
        $this->container['view_type'] = $view_type;

        return $this;
    }

    /**
     * Gets home_team
     *
     * @return string
     */
    public function getHomeTeam()
    {
        return $this->container['home_team'];
    }

    /**
     * Sets home_team
     *
     * @param string $home_team home_team
     *
     * @return self
     */
    public function setHomeTeam($home_team)
    {
        if (is_null($home_team)) {
            throw new \InvalidArgumentException('non-nullable home_team cannot be null');
        }
        $this->container['home_team'] = $home_team;

        return $this;
    }

    /**
     * Gets away_team
     *
     * @return string
     */
    public function getAwayTeam()
    {
        return $this->container['away_team'];
    }

    /**
     * Sets away_team
     *
     * @param string $away_team away_team
     *
     * @return self
     */
    public function setAwayTeam($away_team)
    {
        if (is_null($away_team)) {
            throw new \InvalidArgumentException('non-nullable away_team cannot be null');
        }
        $this->container['away_team'] = $away_team;

        return $this;
    }

    /**
     * Gets home_score
     *
     * @return float
     */
    public function getHomeScore()
    {
        return $this->container['home_score'];
    }

    /**
     * Sets home_score
     *
     * @param float $home_score home_score
     *
     * @return self
     */
    public function setHomeScore($home_score)
    {
        if (is_null($home_score)) {
            throw new \InvalidArgumentException('non-nullable home_score cannot be null');
        }
        $this->container['home_score'] = $home_score;

        return $this;
    }

    /**
     * Gets away_score
     *
     * @return float
     */
    public function getAwayScore()
    {
        return $this->container['away_score'];
    }

    /**
     * Sets away_score
     *
     * @param float $away_score away_score
     *
     * @return self
     */
    public function setAwayScore($away_score)
    {
        if (is_null($away_score)) {
            throw new \InvalidArgumentException('non-nullable away_score cannot be null');
        }
        $this->container['away_score'] = $away_score;

        return $this;
    }

    /**
     * Gets generated_at
     *
     * @return string
     */
    public function getGeneratedAt()
    {
        return $this->container['generated_at'];
    }

    /**
     * Sets generated_at
     *
     * @param string $generated_at ISO 8601 timestamp
     *
     * @return self
     */
    public function setGeneratedAt($generated_at)
    {
        if (is_null($generated_at)) {
            throw new \InvalidArgumentException('non-nullable generated_at cannot be null');
        }
        $this->container['generated_at'] = $generated_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


