<?php
/**
 * GameScoringSummaryDataDto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  VictoryCode\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Victory Code Client API
 *
 * Client APIs for Tactix partners: authenticate, upload game video, and retrieve games, plays, game recaps and team metadata.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace VictoryCode\SDK\Model;

use \ArrayAccess;
use \VictoryCode\SDK\ObjectSerializer;

/**
 * GameScoringSummaryDataDto Class Doc Comment
 *
 * @category Class
 * @package  VictoryCode\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GameScoringSummaryDataDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'GameScoringSummaryDataDto';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'play_id' => 'string',
        'period' => 'string',
        'time_remaining' => 'string',
        'scoring_team_id' => 'string',
        'score_type' => 'string',
        'score_method' => 'string',
        'score_yardage' => 'float',
        'home_score' => 'float',
        'away_score' => 'float'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'play_id' => null,
        'period' => null,
        'time_remaining' => null,
        'scoring_team_id' => null,
        'score_type' => null,
        'score_method' => null,
        'score_yardage' => null,
        'home_score' => null,
        'away_score' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'play_id' => false,
        'period' => false,
        'time_remaining' => false,
        'scoring_team_id' => false,
        'score_type' => false,
        'score_method' => false,
        'score_yardage' => false,
        'home_score' => false,
        'away_score' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'play_id' => 'playId',
        'period' => 'period',
        'time_remaining' => 'timeRemaining',
        'scoring_team_id' => 'scoringTeamId',
        'score_type' => 'scoreType',
        'score_method' => 'scoreMethod',
        'score_yardage' => 'scoreYardage',
        'home_score' => 'homeScore',
        'away_score' => 'awayScore'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'play_id' => 'setPlayId',
        'period' => 'setPeriod',
        'time_remaining' => 'setTimeRemaining',
        'scoring_team_id' => 'setScoringTeamId',
        'score_type' => 'setScoreType',
        'score_method' => 'setScoreMethod',
        'score_yardage' => 'setScoreYardage',
        'home_score' => 'setHomeScore',
        'away_score' => 'setAwayScore'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'play_id' => 'getPlayId',
        'period' => 'getPeriod',
        'time_remaining' => 'getTimeRemaining',
        'scoring_team_id' => 'getScoringTeamId',
        'score_type' => 'getScoreType',
        'score_method' => 'getScoreMethod',
        'score_yardage' => 'getScoreYardage',
        'home_score' => 'getHomeScore',
        'away_score' => 'getAwayScore'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('play_id', $data ?? [], null);
        $this->setIfExists('period', $data ?? [], null);
        $this->setIfExists('time_remaining', $data ?? [], null);
        $this->setIfExists('scoring_team_id', $data ?? [], null);
        $this->setIfExists('score_type', $data ?? [], null);
        $this->setIfExists('score_method', $data ?? [], null);
        $this->setIfExists('score_yardage', $data ?? [], null);
        $this->setIfExists('home_score', $data ?? [], null);
        $this->setIfExists('away_score', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['play_id'] === null) {
            $invalidProperties[] = "'play_id' can't be null";
        }
        if ($this->container['period'] === null) {
            $invalidProperties[] = "'period' can't be null";
        }
        if ($this->container['time_remaining'] === null) {
            $invalidProperties[] = "'time_remaining' can't be null";
        }
        if ($this->container['scoring_team_id'] === null) {
            $invalidProperties[] = "'scoring_team_id' can't be null";
        }
        if ($this->container['score_type'] === null) {
            $invalidProperties[] = "'score_type' can't be null";
        }
        if ($this->container['score_method'] === null) {
            $invalidProperties[] = "'score_method' can't be null";
        }
        if ($this->container['score_yardage'] === null) {
            $invalidProperties[] = "'score_yardage' can't be null";
        }
        if ($this->container['home_score'] === null) {
            $invalidProperties[] = "'home_score' can't be null";
        }
        if ($this->container['away_score'] === null) {
            $invalidProperties[] = "'away_score' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets play_id
     *
     * @return string
     */
    public function getPlayId()
    {
        return $this->container['play_id'];
    }

    /**
     * Sets play_id
     *
     * @param string $play_id play_id
     *
     * @return self
     */
    public function setPlayId($play_id)
    {
        if (is_null($play_id)) {
            throw new \InvalidArgumentException('non-nullable play_id cannot be null');
        }
        $this->container['play_id'] = $play_id;

        return $this;
    }

    /**
     * Gets period
     *
     * @return string
     */
    public function getPeriod()
    {
        return $this->container['period'];
    }

    /**
     * Sets period
     *
     * @param string $period period
     *
     * @return self
     */
    public function setPeriod($period)
    {
        if (is_null($period)) {
            throw new \InvalidArgumentException('non-nullable period cannot be null');
        }
        $this->container['period'] = $period;

        return $this;
    }

    /**
     * Gets time_remaining
     *
     * @return string
     */
    public function getTimeRemaining()
    {
        return $this->container['time_remaining'];
    }

    /**
     * Sets time_remaining
     *
     * @param string $time_remaining time_remaining
     *
     * @return self
     */
    public function setTimeRemaining($time_remaining)
    {
        if (is_null($time_remaining)) {
            throw new \InvalidArgumentException('non-nullable time_remaining cannot be null');
        }
        $this->container['time_remaining'] = $time_remaining;

        return $this;
    }

    /**
     * Gets scoring_team_id
     *
     * @return string
     */
    public function getScoringTeamId()
    {
        return $this->container['scoring_team_id'];
    }

    /**
     * Sets scoring_team_id
     *
     * @param string $scoring_team_id scoring_team_id
     *
     * @return self
     */
    public function setScoringTeamId($scoring_team_id)
    {
        if (is_null($scoring_team_id)) {
            throw new \InvalidArgumentException('non-nullable scoring_team_id cannot be null');
        }
        $this->container['scoring_team_id'] = $scoring_team_id;

        return $this;
    }

    /**
     * Gets score_type
     *
     * @return string
     */
    public function getScoreType()
    {
        return $this->container['score_type'];
    }

    /**
     * Sets score_type
     *
     * @param string $score_type score_type
     *
     * @return self
     */
    public function setScoreType($score_type)
    {
        if (is_null($score_type)) {
            throw new \InvalidArgumentException('non-nullable score_type cannot be null');
        }
        $this->container['score_type'] = $score_type;

        return $this;
    }

    /**
     * Gets score_method
     *
     * @return string
     */
    public function getScoreMethod()
    {
        return $this->container['score_method'];
    }

    /**
     * Sets score_method
     *
     * @param string $score_method score_method
     *
     * @return self
     */
    public function setScoreMethod($score_method)
    {
        if (is_null($score_method)) {
            throw new \InvalidArgumentException('non-nullable score_method cannot be null');
        }
        $this->container['score_method'] = $score_method;

        return $this;
    }

    /**
     * Gets score_yardage
     *
     * @return float
     */
    public function getScoreYardage()
    {
        return $this->container['score_yardage'];
    }

    /**
     * Sets score_yardage
     *
     * @param float $score_yardage score_yardage
     *
     * @return self
     */
    public function setScoreYardage($score_yardage)
    {
        if (is_null($score_yardage)) {
            throw new \InvalidArgumentException('non-nullable score_yardage cannot be null');
        }
        $this->container['score_yardage'] = $score_yardage;

        return $this;
    }

    /**
     * Gets home_score
     *
     * @return float
     */
    public function getHomeScore()
    {
        return $this->container['home_score'];
    }

    /**
     * Sets home_score
     *
     * @param float $home_score home_score
     *
     * @return self
     */
    public function setHomeScore($home_score)
    {
        if (is_null($home_score)) {
            throw new \InvalidArgumentException('non-nullable home_score cannot be null');
        }
        $this->container['home_score'] = $home_score;

        return $this;
    }

    /**
     * Gets away_score
     *
     * @return float
     */
    public function getAwayScore()
    {
        return $this->container['away_score'];
    }

    /**
     * Sets away_score
     *
     * @param float $away_score away_score
     *
     * @return self
     */
    public function setAwayScore($away_score)
    {
        if (is_null($away_score)) {
            throw new \InvalidArgumentException('non-nullable away_score cannot be null');
        }
        $this->container['away_score'] = $away_score;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


