/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.victorycode.sdk.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import ai.victorycode.sdk.models.BadRequestErrorResponseDto
import ai.victorycode.sdk.models.CompleteMultipartUploadDto
import ai.victorycode.sdk.models.CompleteMultipartUploadResponseDto
import ai.victorycode.sdk.models.GetPartsPresignUrlResponseDto
import ai.victorycode.sdk.models.InitiateMultipartUploadDto
import ai.victorycode.sdk.models.InitiateMultipartUploadResponseDto

import com.squareup.moshi.Json

import ai.victorycode.sdk.infrastructure.ApiClient
import ai.victorycode.sdk.infrastructure.ApiResponse
import ai.victorycode.sdk.infrastructure.ClientException
import ai.victorycode.sdk.infrastructure.ClientError
import ai.victorycode.sdk.infrastructure.ServerException
import ai.victorycode.sdk.infrastructure.ServerError
import ai.victorycode.sdk.infrastructure.MultiValueMap
import ai.victorycode.sdk.infrastructure.PartConfig
import ai.victorycode.sdk.infrastructure.RequestConfig
import ai.victorycode.sdk.infrastructure.RequestMethod
import ai.victorycode.sdk.infrastructure.ResponseType
import ai.victorycode.sdk.infrastructure.Success
import ai.victorycode.sdk.infrastructure.toMultiValue

open class UploadsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://sandbox.api.tactixai.com")
        }
    }

    /**
     * POST /api/v1/client/complete-upload
     * Complete a multipart upload to S3
     * 
     * @param completeMultipartUploadDto 
     * @return CompleteMultipartUploadResponseDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun completeMultipartUpload(completeMultipartUploadDto: CompleteMultipartUploadDto) : CompleteMultipartUploadResponseDto {
        val localVarResponse = completeMultipartUploadWithHttpInfo(completeMultipartUploadDto = completeMultipartUploadDto)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CompleteMultipartUploadResponseDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/client/complete-upload
     * Complete a multipart upload to S3
     * 
     * @param completeMultipartUploadDto 
     * @return ApiResponse<CompleteMultipartUploadResponseDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun completeMultipartUploadWithHttpInfo(completeMultipartUploadDto: CompleteMultipartUploadDto) : ApiResponse<CompleteMultipartUploadResponseDto?> {
        val localVariableConfig = completeMultipartUploadRequestConfig(completeMultipartUploadDto = completeMultipartUploadDto)

        return request<CompleteMultipartUploadDto, CompleteMultipartUploadResponseDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation completeMultipartUpload
     *
     * @param completeMultipartUploadDto 
     * @return RequestConfig
     */
    fun completeMultipartUploadRequestConfig(completeMultipartUploadDto: CompleteMultipartUploadDto) : RequestConfig<CompleteMultipartUploadDto> {
        val localVariableBody = completeMultipartUploadDto
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/client/complete-upload",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/client/upload-presigned-url
     * Get a presigned URL for a specific part of a multipart upload
     * 
     * @param uploadId 
     * @param partNumber 
     * @return GetPartsPresignUrlResponseDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getPresignedUrl(uploadId: kotlin.String, partNumber: java.math.BigDecimal) : GetPartsPresignUrlResponseDto {
        val localVarResponse = getPresignedUrlWithHttpInfo(uploadId = uploadId, partNumber = partNumber)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GetPartsPresignUrlResponseDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/client/upload-presigned-url
     * Get a presigned URL for a specific part of a multipart upload
     * 
     * @param uploadId 
     * @param partNumber 
     * @return ApiResponse<GetPartsPresignUrlResponseDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getPresignedUrlWithHttpInfo(uploadId: kotlin.String, partNumber: java.math.BigDecimal) : ApiResponse<GetPartsPresignUrlResponseDto?> {
        val localVariableConfig = getPresignedUrlRequestConfig(uploadId = uploadId, partNumber = partNumber)

        return request<Unit, GetPartsPresignUrlResponseDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getPresignedUrl
     *
     * @param uploadId 
     * @param partNumber 
     * @return RequestConfig
     */
    fun getPresignedUrlRequestConfig(uploadId: kotlin.String, partNumber: java.math.BigDecimal) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("uploadId", listOf(uploadId.toString()))
                put("partNumber", listOf(partNumber.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/client/upload-presigned-url",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /api/v1/client/initiate-upload
     * Initiate a multipart upload to S3 for a large file
     * 
     * @param initiateMultipartUploadDto 
     * @return InitiateMultipartUploadResponseDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun initiateUpload(initiateMultipartUploadDto: InitiateMultipartUploadDto) : InitiateMultipartUploadResponseDto {
        val localVarResponse = initiateUploadWithHttpInfo(initiateMultipartUploadDto = initiateMultipartUploadDto)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as InitiateMultipartUploadResponseDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/client/initiate-upload
     * Initiate a multipart upload to S3 for a large file
     * 
     * @param initiateMultipartUploadDto 
     * @return ApiResponse<InitiateMultipartUploadResponseDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun initiateUploadWithHttpInfo(initiateMultipartUploadDto: InitiateMultipartUploadDto) : ApiResponse<InitiateMultipartUploadResponseDto?> {
        val localVariableConfig = initiateUploadRequestConfig(initiateMultipartUploadDto = initiateMultipartUploadDto)

        return request<InitiateMultipartUploadDto, InitiateMultipartUploadResponseDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation initiateUpload
     *
     * @param initiateMultipartUploadDto 
     * @return RequestConfig
     */
    fun initiateUploadRequestConfig(initiateMultipartUploadDto: InitiateMultipartUploadDto) : RequestConfig<InitiateMultipartUploadDto> {
        val localVariableBody = initiateMultipartUploadDto
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/client/initiate-upload",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
