/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.victorycode.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param fumbles 
 * @param lost 
 * @param recovered 
 */


data class FumbleTotalsDto (

    @Json(name = "fumbles")
    val fumbles: java.math.BigDecimal,

    @Json(name = "lost")
    val lost: java.math.BigDecimal,

    @Json(name = "recovered")
    val recovered: java.math.BigDecimal

) {


}

