/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.victorycode.sdk.models

import ai.victorycode.sdk.models.GetGameRecapTeamStatsResponseDataHomeTeamFirstDowns
import ai.victorycode.sdk.models.GetGameRecapTeamStatsResponseDataHomeTeamOffense
import ai.victorycode.sdk.models.GetGameRecapTeamStatsResponseDataHomeTeamPassing

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param teamId 
 * @param sourceId 
 * @param name 
 * @param mascot 
 * @param classification 
 * @param firstDowns 
 * @param offense 
 * @param passing 
 * @param rushing 
 */


data class GetGameRecapTeamStatsResponseDataHomeTeam (

    @Json(name = "teamId")
    val teamId: kotlin.String? = null,

    @Json(name = "sourceId")
    val sourceId: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "mascot")
    val mascot: kotlin.String? = null,

    @Json(name = "classification")
    val classification: kotlin.String? = null,

    @Json(name = "firstDowns")
    val firstDowns: GetGameRecapTeamStatsResponseDataHomeTeamFirstDowns? = null,

    @Json(name = "offense")
    val offense: GetGameRecapTeamStatsResponseDataHomeTeamOffense? = null,

    @Json(name = "passing")
    val passing: GetGameRecapTeamStatsResponseDataHomeTeamPassing? = null,

    @Json(name = "rushing")
    val rushing: GetGameRecapTeamStatsResponseDataHomeTeamPassing? = null

) {


}

