/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.victorycode.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param carries 
 * @param yards 
 * @param avg 
 * @param touchdowns 
 * @param long Longest rush in yards
 */


data class RushingTotalsDto (

    @Json(name = "carries")
    val carries: java.math.BigDecimal,

    @Json(name = "yards")
    val yards: java.math.BigDecimal,

    @Json(name = "avg")
    val avg: java.math.BigDecimal,

    @Json(name = "touchdowns")
    val touchdowns: java.math.BigDecimal,

    /* Longest rush in yards */
    @Json(name = "long")
    val long: java.math.BigDecimal

) {


}

