/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.victorycode.sdk.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param teamId 
 * @param playerId 
 * @param playerJerseyNumber 
 * @param role 
 */


data class ScoringPlayPlayerInvolvedDto (

    @Json(name = "teamId")
    val teamId: kotlin.String,

    @Json(name = "playerId")
    val playerId: kotlin.String,

    @Json(name = "playerJerseyNumber")
    val playerJerseyNumber: java.math.BigDecimal?,

    @Json(name = "role")
    val role: ScoringPlayPlayerInvolvedDto.Role

) {

    /**
     * 
     *
     * Values: PASSER,RECEIVER,RUSHER,TACKLER,KICKER,RETURNER,PUNTER,HOLDER,DEFENDER,FUMBLER,FUMBLE_RECOVERER
     */
    @JsonClass(generateAdapter = false)
    enum class Role(val value: kotlin.String) {
        @Json(name = "PASSER") PASSER("PASSER"),
        @Json(name = "RECEIVER") RECEIVER("RECEIVER"),
        @Json(name = "RUSHER") RUSHER("RUSHER"),
        @Json(name = "TACKLER") TACKLER("TACKLER"),
        @Json(name = "KICKER") KICKER("KICKER"),
        @Json(name = "RETURNER") RETURNER("RETURNER"),
        @Json(name = "PUNTER") PUNTER("PUNTER"),
        @Json(name = "HOLDER") HOLDER("HOLDER"),
        @Json(name = "DEFENDER") DEFENDER("DEFENDER"),
        @Json(name = "FUMBLER") FUMBLER("FUMBLER"),
        @Json(name = "FUMBLE_RECOVERER") FUMBLE_RECOVERER("FUMBLE_RECOVERER");
    }

}

