//
// ClientCreateGameWithVideoUrlDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ClientCreateGameWithVideoUrlDto: Sendable, Codable, Hashable {

    public enum CompetitionLevel: String, Sendable, Codable, CaseIterable {
        case youth = "YOUTH"
        case highSchool = "HIGH_SCHOOL"
        case college = "COLLEGE"
        case professional = "PROFESSIONAL"
        case amateur = "AMATEUR"
    }
    public enum GameStatus: String, Sendable, Codable, CaseIterable {
        case scheduled = "SCHEDULED"
        case delayed = "DELAYED"
        case inProgress = "IN_PROGRESS"
        case suspended = "SUSPENDED"
        case _final = "FINAL"
        case postponed = "POSTPONED"
        case cancelled = "CANCELLED"
    }
    public var name: String
    public var sourceGameId: String?
    public var s3Link: String
    /** ObjectId of home team */
    public var homeTeam: String
    /** ObjectId of away team */
    public var awayTeam: String
    /** ObjectId of venue */
    public var venue: String
    /** Four-digit year of the game, 1900-2099. Derive it from the game date in the local timezone of the user; spans such as \"2023-24\" are rejected. */
    public var season: String?
    public var week: Double?
    public var competitionLevel: CompetitionLevel?
    public var gameStatus: GameStatus?
    public var gameDateTime: String?
    public var uploadId: String?

    public init(name: String, sourceGameId: String? = nil, s3Link: String, homeTeam: String, awayTeam: String, venue: String, season: String? = nil, week: Double? = nil, competitionLevel: CompetitionLevel? = nil, gameStatus: GameStatus? = nil, gameDateTime: String? = nil, uploadId: String? = nil) {
        self.name = name
        self.sourceGameId = sourceGameId
        self.s3Link = s3Link
        self.homeTeam = homeTeam
        self.awayTeam = awayTeam
        self.venue = venue
        self.season = season
        self.week = week
        self.competitionLevel = competitionLevel
        self.gameStatus = gameStatus
        self.gameDateTime = gameDateTime
        self.uploadId = uploadId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case sourceGameId
        case s3Link
        case homeTeam
        case awayTeam
        case venue
        case season
        case week
        case competitionLevel
        case gameStatus
        case gameDateTime
        case uploadId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(sourceGameId, forKey: .sourceGameId)
        try container.encode(s3Link, forKey: .s3Link)
        try container.encode(homeTeam, forKey: .homeTeam)
        try container.encode(awayTeam, forKey: .awayTeam)
        try container.encode(venue, forKey: .venue)
        try container.encodeIfPresent(season, forKey: .season)
        try container.encodeIfPresent(week, forKey: .week)
        try container.encodeIfPresent(competitionLevel, forKey: .competitionLevel)
        try container.encodeIfPresent(gameStatus, forKey: .gameStatus)
        try container.encodeIfPresent(gameDateTime, forKey: .gameDateTime)
        try container.encodeIfPresent(uploadId, forKey: .uploadId)
    }
}

