//
// CompletedPartDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CompletedPartDto: Sendable, Codable, Hashable {

    public var partNumber: Double
    public var eTag: String

    public init(partNumber: Double, eTag: String) {
        self.partNumber = partNumber
        self.eTag = eTag
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case partNumber
        case eTag = "ETag"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(partNumber, forKey: .partNumber)
        try container.encode(eTag, forKey: .eTag)
    }
}

