//
// GameRecapScoringSummaryProResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GameRecapScoringSummaryProResponse: Sendable, Codable, Hashable {

    public var gameId: String
    public var videoId: String
    public var totalScoringPlays: Double
    public var scoringPlays: [ProScoringPlayDto]

    public init(gameId: String, videoId: String, totalScoringPlays: Double, scoringPlays: [ProScoringPlayDto]) {
        self.gameId = gameId
        self.videoId = videoId
        self.totalScoringPlays = totalScoringPlays
        self.scoringPlays = scoringPlays
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case gameId
        case videoId
        case totalScoringPlays
        case scoringPlays
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(gameId, forKey: .gameId)
        try container.encode(videoId, forKey: .videoId)
        try container.encode(totalScoringPlays, forKey: .totalScoringPlays)
        try container.encode(scoringPlays, forKey: .scoringPlays)
    }
}

