//
// GetGameRecapScoreResponseDataHomeTeam.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetGameRecapScoreResponseDataHomeTeam: Sendable, Codable, Hashable {

    public var teamId: String?
    public var sourceId: String?
    public var name: String?
    public var shortName: String?
    public var mascot: String?
    public var classification: String?
    public var totalScore: Int?
    public var periodScores: [GetGameRecapScoreResponseDataHomeTeamPeriodScoresInner]?

    public init(teamId: String? = nil, sourceId: String? = nil, name: String? = nil, shortName: String? = nil, mascot: String? = nil, classification: String? = nil, totalScore: Int? = nil, periodScores: [GetGameRecapScoreResponseDataHomeTeamPeriodScoresInner]? = nil) {
        self.teamId = teamId
        self.sourceId = sourceId
        self.name = name
        self.shortName = shortName
        self.mascot = mascot
        self.classification = classification
        self.totalScore = totalScore
        self.periodScores = periodScores
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case teamId
        case sourceId
        case name
        case shortName
        case mascot
        case classification
        case totalScore
        case periodScores
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(teamId, forKey: .teamId)
        try container.encodeIfPresent(sourceId, forKey: .sourceId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(shortName, forKey: .shortName)
        try container.encodeIfPresent(mascot, forKey: .mascot)
        try container.encodeIfPresent(classification, forKey: .classification)
        try container.encodeIfPresent(totalScore, forKey: .totalScore)
        try container.encodeIfPresent(periodScores, forKey: .periodScores)
    }
}

