//
// GetGameRecapTeamStatsResponseDataHomeTeam.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetGameRecapTeamStatsResponseDataHomeTeam: Sendable, Codable, Hashable {

    public var teamId: String?
    public var sourceId: String?
    public var name: String?
    public var mascot: String?
    public var classification: String?
    public var firstDowns: GetGameRecapTeamStatsResponseDataHomeTeamFirstDowns?
    public var offense: GetGameRecapTeamStatsResponseDataHomeTeamOffense?
    public var passing: GetGameRecapTeamStatsResponseDataHomeTeamPassing?
    public var rushing: GetGameRecapTeamStatsResponseDataHomeTeamPassing?

    public init(teamId: String? = nil, sourceId: String? = nil, name: String? = nil, mascot: String? = nil, classification: String? = nil, firstDowns: GetGameRecapTeamStatsResponseDataHomeTeamFirstDowns? = nil, offense: GetGameRecapTeamStatsResponseDataHomeTeamOffense? = nil, passing: GetGameRecapTeamStatsResponseDataHomeTeamPassing? = nil, rushing: GetGameRecapTeamStatsResponseDataHomeTeamPassing? = nil) {
        self.teamId = teamId
        self.sourceId = sourceId
        self.name = name
        self.mascot = mascot
        self.classification = classification
        self.firstDowns = firstDowns
        self.offense = offense
        self.passing = passing
        self.rushing = rushing
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case teamId
        case sourceId
        case name
        case mascot
        case classification
        case firstDowns
        case offense
        case passing
        case rushing
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(teamId, forKey: .teamId)
        try container.encodeIfPresent(sourceId, forKey: .sourceId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(mascot, forKey: .mascot)
        try container.encodeIfPresent(classification, forKey: .classification)
        try container.encodeIfPresent(firstDowns, forKey: .firstDowns)
        try container.encodeIfPresent(offense, forKey: .offense)
        try container.encodeIfPresent(passing, forKey: .passing)
        try container.encodeIfPresent(rushing, forKey: .rushing)
    }
}

