//
// KickingTotalsDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct KickingTotalsDto: Sendable, Codable, Hashable {

    /** FG attempts */
    public var fieldGoalsAttempted: Double
    /** FG made */
    public var fieldGoalsMade: Double
    /** PCT — (made / attempted) × 100 */
    public var fieldGoalPct: Double
    /** LONG — longest made field goal in yards */
    public var longFieldGoal: Double
    /** XP attempts */
    public var extraPointsAttempted: Double
    /** XP made */
    public var extraPointsMade: Double
    /** PTS — (FGM×3) + (XPM×1) + (2PC×2) */
    public var totalPoints: Double

    public init(fieldGoalsAttempted: Double, fieldGoalsMade: Double, fieldGoalPct: Double, longFieldGoal: Double, extraPointsAttempted: Double, extraPointsMade: Double, totalPoints: Double) {
        self.fieldGoalsAttempted = fieldGoalsAttempted
        self.fieldGoalsMade = fieldGoalsMade
        self.fieldGoalPct = fieldGoalPct
        self.longFieldGoal = longFieldGoal
        self.extraPointsAttempted = extraPointsAttempted
        self.extraPointsMade = extraPointsMade
        self.totalPoints = totalPoints
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fieldGoalsAttempted
        case fieldGoalsMade
        case fieldGoalPct
        case longFieldGoal
        case extraPointsAttempted
        case extraPointsMade
        case totalPoints
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(fieldGoalsAttempted, forKey: .fieldGoalsAttempted)
        try container.encode(fieldGoalsMade, forKey: .fieldGoalsMade)
        try container.encode(fieldGoalPct, forKey: .fieldGoalPct)
        try container.encode(longFieldGoal, forKey: .longFieldGoal)
        try container.encode(extraPointsAttempted, forKey: .extraPointsAttempted)
        try container.encode(extraPointsMade, forKey: .extraPointsMade)
        try container.encode(totalPoints, forKey: .totalPoints)
    }
}

