//
// ProScoringPlayDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProScoringPlayDto: Sendable, Codable, Hashable {

    public enum ScoringType: String, Sendable, Codable, CaseIterable {
        case touchdown = "TOUCHDOWN"
        case fieldGoal = "FIELD_GOAL"
        case safety = "SAFETY"
    }
    public enum ScoringMethod: String, Sendable, Codable, CaseIterable {
        case run = "RUN"
        case pass = "PASS"
        case fieldGoal = "FIELD_GOAL"
        case kickoff = "KICKOFF"
        case punt = "PUNT"
        case extraPoint = "EXTRA_POINT"
        case twoPointConversion = "TWO_POINT_CONVERSION"
        case noPlay = "NO_PLAY"
        case unidentifiable = "UNIDENTIFIABLE"
    }
    public enum TryType: String, Sendable, Codable, CaseIterable {
        case extraPoint = "EXTRA_POINT"
        case twoPointConversion = "TWO_POINT_CONVERSION"
    }
    public enum TryMethod: String, Sendable, Codable, CaseIterable {
        case run = "RUN"
        case pass = "PASS"
        case fieldGoal = "FIELD_GOAL"
        case kickoff = "KICKOFF"
        case punt = "PUNT"
        case extraPoint = "EXTRA_POINT"
        case twoPointConversion = "TWO_POINT_CONVERSION"
        case noPlay = "NO_PLAY"
        case unidentifiable = "UNIDENTIFIABLE"
    }
    public var driveNumber: Double?
    public var drivePlaysCount: Double
    public var driveYards: Double?
    public var driveTimeOfPossession: String?
    public var playId: String
    public var teamId: String
    public var team: ScoringSummaryProTeamDto
    public var period: Double?
    public var gameClock: String?
    public var scoringType: ScoringType
    public var scoringMethod: ScoringMethod
    public var tryType: TryType?
    public var tryMethod: TryMethod?
    public var scoringYardage: Double
    public var playersInvolved: [ScoringPlayPlayerInvolvedDto]
    public var awayTeamScore: Double
    public var homeTeamScore: Double
    public var scoringText: String

    public init(driveNumber: Double?, drivePlaysCount: Double, driveYards: Double?, driveTimeOfPossession: String?, playId: String, teamId: String, team: ScoringSummaryProTeamDto, period: Double?, gameClock: String?, scoringType: ScoringType, scoringMethod: ScoringMethod, tryType: TryType?, tryMethod: TryMethod?, scoringYardage: Double, playersInvolved: [ScoringPlayPlayerInvolvedDto], awayTeamScore: Double, homeTeamScore: Double, scoringText: String) {
        self.driveNumber = driveNumber
        self.drivePlaysCount = drivePlaysCount
        self.driveYards = driveYards
        self.driveTimeOfPossession = driveTimeOfPossession
        self.playId = playId
        self.teamId = teamId
        self.team = team
        self.period = period
        self.gameClock = gameClock
        self.scoringType = scoringType
        self.scoringMethod = scoringMethod
        self.tryType = tryType
        self.tryMethod = tryMethod
        self.scoringYardage = scoringYardage
        self.playersInvolved = playersInvolved
        self.awayTeamScore = awayTeamScore
        self.homeTeamScore = homeTeamScore
        self.scoringText = scoringText
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case driveNumber
        case drivePlaysCount
        case driveYards
        case driveTimeOfPossession
        case playId
        case teamId
        case team
        case period
        case gameClock
        case scoringType
        case scoringMethod
        case tryType
        case tryMethod
        case scoringYardage
        case playersInvolved
        case awayTeamScore
        case homeTeamScore
        case scoringText
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(driveNumber, forKey: .driveNumber)
        try container.encode(drivePlaysCount, forKey: .drivePlaysCount)
        try container.encode(driveYards, forKey: .driveYards)
        try container.encode(driveTimeOfPossession, forKey: .driveTimeOfPossession)
        try container.encode(playId, forKey: .playId)
        try container.encode(teamId, forKey: .teamId)
        try container.encode(team, forKey: .team)
        try container.encode(period, forKey: .period)
        try container.encode(gameClock, forKey: .gameClock)
        try container.encode(scoringType, forKey: .scoringType)
        try container.encode(scoringMethod, forKey: .scoringMethod)
        try container.encode(tryType, forKey: .tryType)
        try container.encode(tryMethod, forKey: .tryMethod)
        try container.encode(scoringYardage, forKey: .scoringYardage)
        try container.encode(playersInvolved, forKey: .playersInvolved)
        try container.encode(awayTeamScore, forKey: .awayTeamScore)
        try container.encode(homeTeamScore, forKey: .homeTeamScore)
        try container.encode(scoringText, forKey: .scoringText)
    }
}

