/*
 * Victory Code Client API
 * This collection provides the core set of APIs for Tactix clients to interact with the platform. It covers authentication and token management, as well as a wide range of game-related endpoints including uploading full games, fetching generated clips, checking clipping status, retrieving game scoring summaries, and accessing detailed team statistics. All requests are versioned to ensure backward compatibility and smooth upgrades.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.victorycode.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListClassificationsResponseDataInner
 */
public class ListClassificationsResponseDataInnerTest {
    private final ListClassificationsResponseDataInner model = new ListClassificationsResponseDataInner();

    /**
     * Model tests for ListClassificationsResponseDataInner
     */
    @Test
    public void testListClassificationsResponseDataInner() {
        // TODO: test ListClassificationsResponseDataInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'v'
     */
    @Test
    public void vTest() {
        // TODO: test v
    }

}
