/*
 * Victory Code Client API
 * Client APIs for Tactix partners: authenticate, upload game video, and retrieve games, plays, game recaps and team metadata.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.victorycode.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VideoListItemDto
 */
public class VideoListItemDtoTest {
    private final VideoListItemDto model = new VideoListItemDto();

    /**
     * Model tests for VideoListItemDto
     */
    @Test
    public void testVideoListItemDto() {
        // TODO: test VideoListItemDto
    }

    /**
     * Test the property 'gameId'
     */
    @Test
    public void gameIdTest() {
        // TODO: test gameId
    }

    /**
     * Test the property 'videoId'
     */
    @Test
    public void videoIdTest() {
        // TODO: test videoId
    }

    /**
     * Test the property 'viewType'
     */
    @Test
    public void viewTypeTest() {
        // TODO: test viewType
    }

    /**
     * Test the property 'sourceUrl'
     */
    @Test
    public void sourceUrlTest() {
        // TODO: test sourceUrl
    }

    /**
     * Test the property 'isDefaultVideo'
     */
    @Test
    public void isDefaultVideoTest() {
        // TODO: test isDefaultVideo
    }

}
