<?php
/**
 * TeamsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  VictoryCode\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Victory Code Client API
 *
 * This collection provides the core set of APIs for Tactix clients to interact with the platform. It covers authentication and token management, as well as a wide range of game-related endpoints including uploading full games, fetching generated clips, checking clipping status, retrieving game scoring summaries, and accessing detailed team statistics. All requests are versioned to ensure backward compatibility and smooth upgrades.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace VictoryCode\SDK\Test\Api;

use \VictoryCode\SDK\Configuration;
use \VictoryCode\SDK\ApiException;
use \VictoryCode\SDK\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TeamsApiTest Class Doc Comment
 *
 * @category Class
 * @package  VictoryCode\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TeamsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createTeam
     *
     * Create a new team.
     *
     */
    public function testCreateTeam()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteTeam
     *
     * Delete a team.
     *
     */
    public function testDeleteTeam()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listTeams
     *
     * Get teams.
     *
     */
    public function testListTeams()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateTeam
     *
     * Update a team.
     *
     */
    public function testUpdateTeam()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
