/* tslint:disable */
/* eslint-disable */
/**
 * Victory Code Client API
 * This collection provides the core set of APIs for Tactix clients to interact with the platform. It covers authentication and token management, as well as a wide range of game-related endpoints including uploading full games, fetching generated clips, checking clipping status, retrieving game scoring summaries, and accessing detailed team statistics. All requests are versioned to ensure backward compatibility and smooth upgrades.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateTeamResponseData } from './CreateTeamResponseData';
import {
    CreateTeamResponseDataFromJSON,
    CreateTeamResponseDataFromJSONTyped,
    CreateTeamResponseDataToJSON,
    CreateTeamResponseDataToJSONTyped,
} from './CreateTeamResponseData';

/**
 * 
 * @export
 * @interface CreateTeamResponse
 */
export interface CreateTeamResponse {
    /**
     * 
     */
    message?: string;
    /**
     * 
     */
    data?: CreateTeamResponseData;
}

/**
 * Check if a given object implements the CreateTeamResponse interface.
 */
export function instanceOfCreateTeamResponse(value: object): value is CreateTeamResponse {
    return true;
}

export function CreateTeamResponseFromJSON(json: any): CreateTeamResponse {
    return CreateTeamResponseFromJSONTyped(json, false);
}

export function CreateTeamResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTeamResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : CreateTeamResponseDataFromJSON(json['data']),
    };
}

export function CreateTeamResponseToJSON(json: any): CreateTeamResponse {
    return CreateTeamResponseToJSONTyped(json, false);
}

export function CreateTeamResponseToJSONTyped(value?: CreateTeamResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'data': CreateTeamResponseDataToJSON(value['data']),
    };
}

