/* tslint:disable */
/* eslint-disable */
/**
 * Victory Code Client API
 * Client APIs for Tactix partners: authenticate, upload game video, and retrieve games, plays, game recaps and team metadata.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DownEfficiencyDto
 */
export interface DownEfficiencyDto {
    /**
     * 
     */
    down: number;
    /**
     * 
     */
    conversions: number;
}

/**
 * Check if a given object implements the DownEfficiencyDto interface.
 */
export function instanceOfDownEfficiencyDto(value: object): value is DownEfficiencyDto {
    if (!('down' in value) || value['down'] === undefined) return false;
    if (!('conversions' in value) || value['conversions'] === undefined) return false;
    return true;
}

export function DownEfficiencyDtoFromJSON(json: any): DownEfficiencyDto {
    return DownEfficiencyDtoFromJSONTyped(json, false);
}

export function DownEfficiencyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DownEfficiencyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'down': json['down'],
        'conversions': json['conversions'],
    };
}

export function DownEfficiencyDtoToJSON(json: any): DownEfficiencyDto {
    return DownEfficiencyDtoToJSONTyped(json, false);
}

export function DownEfficiencyDtoToJSONTyped(value?: DownEfficiencyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'down': value['down'],
        'conversions': value['conversions'],
    };
}

