/* tslint:disable */
/* eslint-disable */
/**
 * Victory Code Client API
 * Client APIs for Tactix partners: authenticate, upload game video, and retrieve games, plays, game recaps and team metadata.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PlayAttributesListDto } from './PlayAttributesListDto';
import {
    PlayAttributesListDtoFromJSON,
    PlayAttributesListDtoToJSON,
} from './PlayAttributesListDto';
import type { PlayClipListDetailsDto } from './PlayClipListDetailsDto';
import {
    PlayClipListDetailsDtoFromJSON,
    PlayClipListDetailsDtoToJSON,
} from './PlayClipListDetailsDto';

/**
 * 
 * @export
 * @interface GameAllPlayListItemDto
 */
export interface GameAllPlayListItemDto {
    /**
     * 
     */
    playId: string;
    /**
     * 
     */
    playNumber: number;
    /**
     * 
     */
    clip: PlayClipListDetailsDto;
    /**
     * 
     */
    attributes: PlayAttributesListDto;
    /**
     * 
     */
    events: Array<object>;
    /**
     * 
     */
    videoId: string;
}

/**
 * Check if a given object implements the GameAllPlayListItemDto interface.
 */
export function instanceOfGameAllPlayListItemDto(value: object): value is GameAllPlayListItemDto {
    if (!('playId' in value) || value['playId'] === undefined) return false;
    if (!('playNumber' in value) || value['playNumber'] === undefined) return false;
    if (!('clip' in value) || value['clip'] === undefined) return false;
    if (!('attributes' in value) || value['attributes'] === undefined) return false;
    if (!('events' in value) || value['events'] === undefined) return false;
    if (!('videoId' in value) || value['videoId'] === undefined) return false;
    return true;
}

export function GameAllPlayListItemDtoFromJSON(json: any): GameAllPlayListItemDto {
    return GameAllPlayListItemDtoFromJSONTyped(json, false);
}

export function GameAllPlayListItemDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameAllPlayListItemDto {
    if (json == null) {
        return json;
    }
    return {
        
        'playId': json['playId'],
        'playNumber': json['playNumber'],
        'clip': PlayClipListDetailsDtoFromJSON(json['clip']),
        'attributes': PlayAttributesListDtoFromJSON(json['attributes']),
        'events': json['events'],
        'videoId': json['videoId'],
    };
}

export function GameAllPlayListItemDtoToJSON(json: any): GameAllPlayListItemDto {
    return GameAllPlayListItemDtoToJSONTyped(json, false);
}

export function GameAllPlayListItemDtoToJSONTyped(value?: GameAllPlayListItemDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'playId': value['playId'],
        'playNumber': value['playNumber'],
        'clip': PlayClipListDetailsDtoToJSON(value['clip']),
        'attributes': PlayAttributesListDtoToJSON(value['attributes']),
        'events': value['events'],
        'videoId': value['videoId'],
    };
}

