/* tslint:disable */
/* eslint-disable */
/**
 * Victory Code Client API
 * This collection provides the core set of APIs for Tactix clients to interact with the platform. It covers authentication and token management, as well as a wide range of game-related endpoints including uploading full games, fetching generated clips, checking clipping status, retrieving game scoring summaries, and accessing detailed team statistics. All requests are versioned to ensure backward compatibility and smooth upgrades.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetGameResponseDataHomeTeam
 */
export interface GetGameResponseDataHomeTeam {
    /**
     * 
     */
    teamId?: string;
    /**
     * 
     */
    name?: string;
    /**
     * 
     */
    shortName?: string;
    /**
     * 
     */
    mascot?: string;
    /**
     * 
     */
    classification?: string;
}

/**
 * Check if a given object implements the GetGameResponseDataHomeTeam interface.
 */
export function instanceOfGetGameResponseDataHomeTeam(value: object): value is GetGameResponseDataHomeTeam {
    return true;
}

export function GetGameResponseDataHomeTeamFromJSON(json: any): GetGameResponseDataHomeTeam {
    return GetGameResponseDataHomeTeamFromJSONTyped(json, false);
}

export function GetGameResponseDataHomeTeamFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetGameResponseDataHomeTeam {
    if (json == null) {
        return json;
    }
    return {
        
        'teamId': json['teamId'] == null ? undefined : json['teamId'],
        'name': json['name'] == null ? undefined : json['name'],
        'shortName': json['shortName'] == null ? undefined : json['shortName'],
        'mascot': json['mascot'] == null ? undefined : json['mascot'],
        'classification': json['classification'] == null ? undefined : json['classification'],
    };
}

export function GetGameResponseDataHomeTeamToJSON(json: any): GetGameResponseDataHomeTeam {
    return GetGameResponseDataHomeTeamToJSONTyped(json, false);
}

export function GetGameResponseDataHomeTeamToJSONTyped(value?: GetGameResponseDataHomeTeam | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'teamId': value['teamId'],
        'name': value['name'],
        'shortName': value['shortName'],
        'mascot': value['mascot'],
        'classification': value['classification'],
    };
}

