/* tslint:disable */
/* eslint-disable */
/**
 * Victory Code Client API
 * Client APIs for Tactix partners: authenticate, upload game video, and retrieve games, plays, game recaps and team metadata.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PassingTotalsDto } from './PassingTotalsDto';
import {
    PassingTotalsDtoFromJSON,
    PassingTotalsDtoFromJSONTyped,
    PassingTotalsDtoToJSON,
    PassingTotalsDtoToJSONTyped,
} from './PassingTotalsDto';
import type { PassingStatsDto } from './PassingStatsDto';
import {
    PassingStatsDtoFromJSON,
    PassingStatsDtoFromJSONTyped,
    PassingStatsDtoToJSON,
    PassingStatsDtoToJSONTyped,
} from './PassingStatsDto';

/**
 * 
 * @export
 * @interface PassingSectionDto
 */
export interface PassingSectionDto {
    /**
     * 
     */
    players: Array<PassingStatsDto>;
    /**
     * 
     */
    totals: PassingTotalsDto;
}

/**
 * Check if a given object implements the PassingSectionDto interface.
 */
export function instanceOfPassingSectionDto(value: object): value is PassingSectionDto {
    if (!('players' in value) || value['players'] === undefined) return false;
    if (!('totals' in value) || value['totals'] === undefined) return false;
    return true;
}

export function PassingSectionDtoFromJSON(json: any): PassingSectionDto {
    return PassingSectionDtoFromJSONTyped(json, false);
}

export function PassingSectionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PassingSectionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'players': ((json['players'] as Array<any>).map(PassingStatsDtoFromJSON)),
        'totals': PassingTotalsDtoFromJSON(json['totals']),
    };
}

export function PassingSectionDtoToJSON(json: any): PassingSectionDto {
    return PassingSectionDtoToJSONTyped(json, false);
}

export function PassingSectionDtoToJSONTyped(value?: PassingSectionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'players': ((value['players'] as Array<any>).map(PassingStatsDtoToJSON)),
        'totals': PassingTotalsDtoToJSON(value['totals']),
    };
}

