/* tslint:disable */
/* eslint-disable */
/**
 * Victory Code Client API
 * Client APIs for Tactix partners: authenticate, upload game video, and retrieve games, plays, game recaps and team metadata.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CoordinatesDto } from './CoordinatesDto';
import {
    CoordinatesDtoFromJSON,
    CoordinatesDtoFromJSONTyped,
    CoordinatesDtoToJSON,
    CoordinatesDtoToJSONTyped,
} from './CoordinatesDto';
import type { AddressDto } from './AddressDto';
import {
    AddressDtoFromJSON,
    AddressDtoFromJSONTyped,
    AddressDtoToJSON,
    AddressDtoToJSONTyped,
} from './AddressDto';

/**
 * 
 * @export
 * @interface UpdateVenueDto
 */
export interface UpdateVenueDto {
    /**
     * 
     */
    name?: string;
    /**
     * 
     */
    playingSurface?: string;
    /**
     * 
     */
    address?: AddressDto;
    /**
     * 
     */
    coordinates?: CoordinatesDto;
}

/**
 * Check if a given object implements the UpdateVenueDto interface.
 */
export function instanceOfUpdateVenueDto(value: object): value is UpdateVenueDto {
    return true;
}

export function UpdateVenueDtoFromJSON(json: any): UpdateVenueDto {
    return UpdateVenueDtoFromJSONTyped(json, false);
}

export function UpdateVenueDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateVenueDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'playingSurface': json['playingSurface'] == null ? undefined : json['playingSurface'],
        'address': json['address'] == null ? undefined : AddressDtoFromJSON(json['address']),
        'coordinates': json['coordinates'] == null ? undefined : CoordinatesDtoFromJSON(json['coordinates']),
    };
}

export function UpdateVenueDtoToJSON(json: any): UpdateVenueDto {
    return UpdateVenueDtoToJSONTyped(json, false);
}

export function UpdateVenueDtoToJSONTyped(value?: UpdateVenueDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'playingSurface': value['playingSurface'],
        'address': AddressDtoToJSON(value['address']),
        'coordinates': CoordinatesDtoToJSON(value['coordinates']),
    };
}

