# coding: utf-8

# flake8: noqa

"""
    Victory Code Client API

    This collection provides the core set of APIs for Tactix clients to interact with the platform. It covers authentication and token management, as well as a wide range of game-related endpoints including uploading full games, fetching generated clips, checking clipping status, retrieving game scoring summaries, and accessing detailed team statistics. All requests are versioned to ensure backward compatibility and smooth upgrades.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.1.0"

# Define package exports
__all__ = [
    "AuthApi",
    "ClassificationsApi",
    "GameRecapApi",
    "GamesApi",
    "MascotsApi",
    "TeamsApi",
    "UploadsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "CreateClassificationRequest",
    "CreateClassificationResponse",
    "CreateClassificationResponseData",
    "CreateMascotResponse",
    "CreateMascotResponseData",
    "CreateTeamResponse",
    "CreateTeamResponseData",
    "DeleteClassificationResponse",
    "DeleteMascotResponse",
    "DeleteTeamResponse",
    "GenerateAccessTokenResponse",
    "GetGameRecapScoreResponse",
    "GetGameRecapScoreResponseData",
    "GetGameRecapScoreResponseDataHomeTeam",
    "GetGameRecapScoreResponseDataHomeTeamPeriodScoresInner",
    "GetGameRecapScoringSummaryResponse",
    "GetGameRecapScoringSummaryResponseData",
    "GetGameRecapScoringSummaryResponseDataDataInnerInner",
    "GetGameRecapTeamStatsResponse",
    "GetGameRecapTeamStatsResponseData",
    "GetGameRecapTeamStatsResponseDataHomeTeam",
    "GetGameRecapTeamStatsResponseDataHomeTeamFirstDowns",
    "GetGameRecapTeamStatsResponseDataHomeTeamOffense",
    "GetGameRecapTeamStatsResponseDataHomeTeamPassing",
    "GetGameResponse",
    "GetGameResponseData",
    "GetGameResponseDataHomeTeam",
    "GetUploadStatusResponse",
    "GetUploadStatusResponseData",
    "ListClassificationsResponse",
    "ListClassificationsResponseDataInner",
    "ListClassificationsResponsePagination",
    "ListGamesResponse",
    "ListGamesResponseData",
    "ListGamesResponseDataGamesInner",
    "ListGamesResponseDataGamesInnerHomeTeam",
    "ListMascotsResponse",
    "ListMascotsResponseDataInner",
    "UpdateClassificationRequest",
    "UpdateClassificationResponse",
    "UpdateMascotResponse",
    "UploadVideoAndCreateGameResponse",
    "UploadVideoAndCreateGameResponseData",
]

# import apis into sdk package
from victorycode_sdk.api.auth_api import AuthApi as AuthApi
from victorycode_sdk.api.classifications_api import ClassificationsApi as ClassificationsApi
from victorycode_sdk.api.game_recap_api import GameRecapApi as GameRecapApi
from victorycode_sdk.api.games_api import GamesApi as GamesApi
from victorycode_sdk.api.mascots_api import MascotsApi as MascotsApi
from victorycode_sdk.api.teams_api import TeamsApi as TeamsApi
from victorycode_sdk.api.uploads_api import UploadsApi as UploadsApi

# import ApiClient
from victorycode_sdk.api_response import ApiResponse as ApiResponse
from victorycode_sdk.api_client import ApiClient as ApiClient
from victorycode_sdk.configuration import Configuration as Configuration
from victorycode_sdk.exceptions import OpenApiException as OpenApiException
from victorycode_sdk.exceptions import ApiTypeError as ApiTypeError
from victorycode_sdk.exceptions import ApiValueError as ApiValueError
from victorycode_sdk.exceptions import ApiKeyError as ApiKeyError
from victorycode_sdk.exceptions import ApiAttributeError as ApiAttributeError
from victorycode_sdk.exceptions import ApiException as ApiException

# import models into sdk package
from victorycode_sdk.models.create_classification_request import CreateClassificationRequest as CreateClassificationRequest
from victorycode_sdk.models.create_classification_response import CreateClassificationResponse as CreateClassificationResponse
from victorycode_sdk.models.create_classification_response_data import CreateClassificationResponseData as CreateClassificationResponseData
from victorycode_sdk.models.create_mascot_response import CreateMascotResponse as CreateMascotResponse
from victorycode_sdk.models.create_mascot_response_data import CreateMascotResponseData as CreateMascotResponseData
from victorycode_sdk.models.create_team_response import CreateTeamResponse as CreateTeamResponse
from victorycode_sdk.models.create_team_response_data import CreateTeamResponseData as CreateTeamResponseData
from victorycode_sdk.models.delete_classification_response import DeleteClassificationResponse as DeleteClassificationResponse
from victorycode_sdk.models.delete_mascot_response import DeleteMascotResponse as DeleteMascotResponse
from victorycode_sdk.models.delete_team_response import DeleteTeamResponse as DeleteTeamResponse
from victorycode_sdk.models.generate_access_token_response import GenerateAccessTokenResponse as GenerateAccessTokenResponse
from victorycode_sdk.models.get_game_recap_score_response import GetGameRecapScoreResponse as GetGameRecapScoreResponse
from victorycode_sdk.models.get_game_recap_score_response_data import GetGameRecapScoreResponseData as GetGameRecapScoreResponseData
from victorycode_sdk.models.get_game_recap_score_response_data_home_team import GetGameRecapScoreResponseDataHomeTeam as GetGameRecapScoreResponseDataHomeTeam
from victorycode_sdk.models.get_game_recap_score_response_data_home_team_period_scores_inner import GetGameRecapScoreResponseDataHomeTeamPeriodScoresInner as GetGameRecapScoreResponseDataHomeTeamPeriodScoresInner
from victorycode_sdk.models.get_game_recap_scoring_summary_response import GetGameRecapScoringSummaryResponse as GetGameRecapScoringSummaryResponse
from victorycode_sdk.models.get_game_recap_scoring_summary_response_data import GetGameRecapScoringSummaryResponseData as GetGameRecapScoringSummaryResponseData
from victorycode_sdk.models.get_game_recap_scoring_summary_response_data_data_inner_inner import GetGameRecapScoringSummaryResponseDataDataInnerInner as GetGameRecapScoringSummaryResponseDataDataInnerInner
from victorycode_sdk.models.get_game_recap_team_stats_response import GetGameRecapTeamStatsResponse as GetGameRecapTeamStatsResponse
from victorycode_sdk.models.get_game_recap_team_stats_response_data import GetGameRecapTeamStatsResponseData as GetGameRecapTeamStatsResponseData
from victorycode_sdk.models.get_game_recap_team_stats_response_data_home_team import GetGameRecapTeamStatsResponseDataHomeTeam as GetGameRecapTeamStatsResponseDataHomeTeam
from victorycode_sdk.models.get_game_recap_team_stats_response_data_home_team_first_downs import GetGameRecapTeamStatsResponseDataHomeTeamFirstDowns as GetGameRecapTeamStatsResponseDataHomeTeamFirstDowns
from victorycode_sdk.models.get_game_recap_team_stats_response_data_home_team_offense import GetGameRecapTeamStatsResponseDataHomeTeamOffense as GetGameRecapTeamStatsResponseDataHomeTeamOffense
from victorycode_sdk.models.get_game_recap_team_stats_response_data_home_team_passing import GetGameRecapTeamStatsResponseDataHomeTeamPassing as GetGameRecapTeamStatsResponseDataHomeTeamPassing
from victorycode_sdk.models.get_game_response import GetGameResponse as GetGameResponse
from victorycode_sdk.models.get_game_response_data import GetGameResponseData as GetGameResponseData
from victorycode_sdk.models.get_game_response_data_home_team import GetGameResponseDataHomeTeam as GetGameResponseDataHomeTeam
from victorycode_sdk.models.get_upload_status_response import GetUploadStatusResponse as GetUploadStatusResponse
from victorycode_sdk.models.get_upload_status_response_data import GetUploadStatusResponseData as GetUploadStatusResponseData
from victorycode_sdk.models.list_classifications_response import ListClassificationsResponse as ListClassificationsResponse
from victorycode_sdk.models.list_classifications_response_data_inner import ListClassificationsResponseDataInner as ListClassificationsResponseDataInner
from victorycode_sdk.models.list_classifications_response_pagination import ListClassificationsResponsePagination as ListClassificationsResponsePagination
from victorycode_sdk.models.list_games_response import ListGamesResponse as ListGamesResponse
from victorycode_sdk.models.list_games_response_data import ListGamesResponseData as ListGamesResponseData
from victorycode_sdk.models.list_games_response_data_games_inner import ListGamesResponseDataGamesInner as ListGamesResponseDataGamesInner
from victorycode_sdk.models.list_games_response_data_games_inner_home_team import ListGamesResponseDataGamesInnerHomeTeam as ListGamesResponseDataGamesInnerHomeTeam
from victorycode_sdk.models.list_mascots_response import ListMascotsResponse as ListMascotsResponse
from victorycode_sdk.models.list_mascots_response_data_inner import ListMascotsResponseDataInner as ListMascotsResponseDataInner
from victorycode_sdk.models.update_classification_request import UpdateClassificationRequest as UpdateClassificationRequest
from victorycode_sdk.models.update_classification_response import UpdateClassificationResponse as UpdateClassificationResponse
from victorycode_sdk.models.update_mascot_response import UpdateMascotResponse as UpdateMascotResponse
from victorycode_sdk.models.upload_video_and_create_game_response import UploadVideoAndCreateGameResponse as UploadVideoAndCreateGameResponse
from victorycode_sdk.models.upload_video_and_create_game_response_data import UploadVideoAndCreateGameResponseData as UploadVideoAndCreateGameResponseData

