/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.tactixai.victorycode.sdk.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import com.tactixai.victorycode.sdk.models.BadRequestErrorResponseDto
import com.tactixai.victorycode.sdk.models.ConflictErrorResponseDto
import com.tactixai.victorycode.sdk.models.CreateClassificationDto
import com.tactixai.victorycode.sdk.models.DeleteResponseDto
import com.tactixai.victorycode.sdk.models.ListClassificationPaginatedResponseDto
import com.tactixai.victorycode.sdk.models.NotFoundErrorResponseDto
import com.tactixai.victorycode.sdk.models.SingleClassificationResponseDto
import com.tactixai.victorycode.sdk.models.UnauthorizedErrorResponseDto
import com.tactixai.victorycode.sdk.models.UpdateClassificationDto

import com.squareup.moshi.Json

import com.tactixai.victorycode.sdk.infrastructure.ApiClient
import com.tactixai.victorycode.sdk.infrastructure.ApiResponse
import com.tactixai.victorycode.sdk.infrastructure.ClientException
import com.tactixai.victorycode.sdk.infrastructure.ClientError
import com.tactixai.victorycode.sdk.infrastructure.ServerException
import com.tactixai.victorycode.sdk.infrastructure.ServerError
import com.tactixai.victorycode.sdk.infrastructure.MultiValueMap
import com.tactixai.victorycode.sdk.infrastructure.PartConfig
import com.tactixai.victorycode.sdk.infrastructure.RequestConfig
import com.tactixai.victorycode.sdk.infrastructure.RequestMethod
import com.tactixai.victorycode.sdk.infrastructure.ResponseType
import com.tactixai.victorycode.sdk.infrastructure.Success
import com.tactixai.victorycode.sdk.infrastructure.toMultiValue

open class ClassificationApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://sandbox.api.tactixai.com")
        }
    }

    /**
     * POST /api/v1/client/classifications
     * Create a new classification
     * Creates a new classification entry for categorizing teams.
     * @param createClassificationDto 
     * @return SingleClassificationResponseDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createClassification(createClassificationDto: CreateClassificationDto) : SingleClassificationResponseDto {
        val localVarResponse = createClassificationWithHttpInfo(createClassificationDto = createClassificationDto)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SingleClassificationResponseDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/v1/client/classifications
     * Create a new classification
     * Creates a new classification entry for categorizing teams.
     * @param createClassificationDto 
     * @return ApiResponse<SingleClassificationResponseDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createClassificationWithHttpInfo(createClassificationDto: CreateClassificationDto) : ApiResponse<SingleClassificationResponseDto?> {
        val localVariableConfig = createClassificationRequestConfig(createClassificationDto = createClassificationDto)

        return request<CreateClassificationDto, SingleClassificationResponseDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createClassification
     *
     * @param createClassificationDto 
     * @return RequestConfig
     */
    fun createClassificationRequestConfig(createClassificationDto: CreateClassificationDto) : RequestConfig<CreateClassificationDto> {
        val localVariableBody = createClassificationDto
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/v1/client/classifications",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /api/v1/client/classifications/{id}
     * Delete a classification
     * Permanently deletes a team classification from the system.
     * @param id 
     * @return DeleteResponseDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun deleteClassification(id: kotlin.String) : DeleteResponseDto {
        val localVarResponse = deleteClassificationWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as DeleteResponseDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /api/v1/client/classifications/{id}
     * Delete a classification
     * Permanently deletes a team classification from the system.
     * @param id 
     * @return ApiResponse<DeleteResponseDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun deleteClassificationWithHttpInfo(id: kotlin.String) : ApiResponse<DeleteResponseDto?> {
        val localVariableConfig = deleteClassificationRequestConfig(id = id)

        return request<Unit, DeleteResponseDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation deleteClassification
     *
     * @param id 
     * @return RequestConfig
     */
    fun deleteClassificationRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/api/v1/client/classifications/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /api/v1/client/classifications
     * Get all classifications
     * Retrieves a paginated list of all team classifications available in the system.
     * @param limit  (optional, default to 10)
     * @param page  (optional, default to 1)
     * @param search  (optional)
     * @return ListClassificationPaginatedResponseDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getClassifications(limit: java.math.BigDecimal? = java.math.BigDecimal("10"), page: java.math.BigDecimal? = java.math.BigDecimal("1"), search: kotlin.String? = null) : ListClassificationPaginatedResponseDto {
        val localVarResponse = getClassificationsWithHttpInfo(limit = limit, page = page, search = search)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ListClassificationPaginatedResponseDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /api/v1/client/classifications
     * Get all classifications
     * Retrieves a paginated list of all team classifications available in the system.
     * @param limit  (optional, default to 10)
     * @param page  (optional, default to 1)
     * @param search  (optional)
     * @return ApiResponse<ListClassificationPaginatedResponseDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getClassificationsWithHttpInfo(limit: java.math.BigDecimal?, page: java.math.BigDecimal?, search: kotlin.String?) : ApiResponse<ListClassificationPaginatedResponseDto?> {
        val localVariableConfig = getClassificationsRequestConfig(limit = limit, page = page, search = search)

        return request<Unit, ListClassificationPaginatedResponseDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getClassifications
     *
     * @param limit  (optional, default to 10)
     * @param page  (optional, default to 1)
     * @param search  (optional)
     * @return RequestConfig
     */
    fun getClassificationsRequestConfig(limit: java.math.BigDecimal?, page: java.math.BigDecimal?, search: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                if (limit != null) {
                    put("limit", listOf(limit.toString()))
                }
                if (page != null) {
                    put("page", listOf(page.toString()))
                }
                if (search != null) {
                    put("search", listOf(search.toString()))
                }
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/api/v1/client/classifications",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /api/v1/client/classifications/{id}
     * Update a classification
     * Updates an existing team classification entry identified by its ID.
     * @param id 
     * @param updateClassificationDto 
     * @return SingleClassificationResponseDto
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updateClassification(id: kotlin.String, updateClassificationDto: UpdateClassificationDto) : SingleClassificationResponseDto {
        val localVarResponse = updateClassificationWithHttpInfo(id = id, updateClassificationDto = updateClassificationDto)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as SingleClassificationResponseDto
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /api/v1/client/classifications/{id}
     * Update a classification
     * Updates an existing team classification entry identified by its ID.
     * @param id 
     * @param updateClassificationDto 
     * @return ApiResponse<SingleClassificationResponseDto?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun updateClassificationWithHttpInfo(id: kotlin.String, updateClassificationDto: UpdateClassificationDto) : ApiResponse<SingleClassificationResponseDto?> {
        val localVariableConfig = updateClassificationRequestConfig(id = id, updateClassificationDto = updateClassificationDto)

        return request<UpdateClassificationDto, SingleClassificationResponseDto>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updateClassification
     *
     * @param id 
     * @param updateClassificationDto 
     * @return RequestConfig
     */
    fun updateClassificationRequestConfig(id: kotlin.String, updateClassificationDto: UpdateClassificationDto) : RequestConfig<UpdateClassificationDto> {
        val localVariableBody = updateClassificationDto
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/api/v1/client/classifications/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
