/*
 * Victory Code Client API
 * Client APIs for Tactix partners: authenticate, upload game video, and retrieve games, plays, game recaps and team metadata.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tactixai.victorycode.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.tactixai.victorycode.sdk.model.PlayAttributesListDto;
import com.tactixai.victorycode.sdk.model.PlayClipListDetailsDto;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PlayClipListItemDto
 */
public class PlayClipListItemDtoTest {
    private final PlayClipListItemDto model = new PlayClipListItemDto();

    /**
     * Model tests for PlayClipListItemDto
     */
    @Test
    public void testPlayClipListItemDto() {
        // TODO: test PlayClipListItemDto
    }

    /**
     * Test the property 'playId'
     */
    @Test
    public void playIdTest() {
        // TODO: test playId
    }

    /**
     * Test the property 'playNumber'
     */
    @Test
    public void playNumberTest() {
        // TODO: test playNumber
    }

    /**
     * Test the property 'clip'
     */
    @Test
    public void clipTest() {
        // TODO: test clip
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

    /**
     * Test the property 'events'
     */
    @Test
    public void eventsTest() {
        // TODO: test events
    }

}
