/* tslint:disable */
/* eslint-disable */
/**
 * Victory Code Client API
 * This collection provides the core set of APIs for Tactix clients to interact with the platform. It covers authentication and token management, as well as a wide range of game-related endpoints including uploading full games, fetching generated clips, checking clipping status, retrieving game scoring summaries, and accessing detailed team statistics. All requests are versioned to ensure backward compatibility and smooth upgrades.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateClassificationRequest,
    CreateClassificationRequestFromJSON,
    CreateClassificationRequestToJSON,
} from '../models/CreateClassificationRequest';
import {
    type CreateClassificationResponse,
    CreateClassificationResponseFromJSON,
    CreateClassificationResponseToJSON,
} from '../models/CreateClassificationResponse';
import {
    type DeleteClassificationResponse,
    DeleteClassificationResponseFromJSON,
    DeleteClassificationResponseToJSON,
} from '../models/DeleteClassificationResponse';
import {
    type ListClassificationsResponse,
    ListClassificationsResponseFromJSON,
    ListClassificationsResponseToJSON,
} from '../models/ListClassificationsResponse';
import {
    type UpdateClassificationRequest,
    UpdateClassificationRequestFromJSON,
    UpdateClassificationRequestToJSON,
} from '../models/UpdateClassificationRequest';
import {
    type UpdateClassificationResponse,
    UpdateClassificationResponseFromJSON,
    UpdateClassificationResponseToJSON,
} from '../models/UpdateClassificationResponse';

export interface CreateClassificationOperationRequest {
    /**
     * 
     */
    createClassificationRequest: CreateClassificationRequest;
}

export interface DeleteClassificationRequest {
    /**
     * 
     */
    id: string;
}

export interface ListClassificationsRequest {
    /**
     * 
     */
    limit?: number;
    /**
     * 
     */
    page?: number;
}

export interface UpdateClassificationOperationRequest {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    updateClassificationRequest: UpdateClassificationRequest;
}

/**
 * 
 */
export class ClassificationsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createClassification without sending the request
     */
    async createClassificationRequestOpts(requestParameters: CreateClassificationOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createClassificationRequest'] == null) {
            throw new runtime.RequiredError(
                'createClassificationRequest',
                'Required parameter "createClassificationRequest" was null or undefined when calling createClassification().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["App-Token"] = await this.configuration.apiKey("App-Token"); // AppToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["App-Id"] = await this.configuration.apiKey("App-Id"); // AppId authentication
        }


        let urlPath = `/api/v1/client/classifications`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateClassificationRequestToJSON(requestParameters['createClassificationRequest']),
        };
    }

    /**
     * Creates a new classification record in the Tactix platform. Classifications are used to categorize teams by league, division, or competition level (e.g., “Division 1A”, “Junior Varsity”).
     * Create a new classification
     */
    async createClassificationRaw(requestParameters: CreateClassificationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateClassificationResponse>> {
        const requestOptions = await this.createClassificationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateClassificationResponseFromJSON(jsonValue));
    }

    /**
     * Creates a new classification record in the Tactix platform. Classifications are used to categorize teams by league, division, or competition level (e.g., “Division 1A”, “Junior Varsity”).
     * Create a new classification
     */
    async createClassification(requestParameters: CreateClassificationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateClassificationResponse> {
        const response = await this.createClassificationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteClassification without sending the request
     */
    async deleteClassificationRequestOpts(requestParameters: DeleteClassificationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteClassification().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["App-Token"] = await this.configuration.apiKey("App-Token"); // AppToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["App-Id"] = await this.configuration.apiKey("App-Id"); // AppId authentication
        }


        let urlPath = `/api/v1/client/classifications/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Deletes a specific classification from the Tactix system using its unique id. This permanently removes the classification and disassociates it from any linked team records.
     * Delete a classification
     */
    async deleteClassificationRaw(requestParameters: DeleteClassificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteClassificationResponse>> {
        const requestOptions = await this.deleteClassificationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteClassificationResponseFromJSON(jsonValue));
    }

    /**
     * Deletes a specific classification from the Tactix system using its unique id. This permanently removes the classification and disassociates it from any linked team records.
     * Delete a classification
     */
    async deleteClassification(requestParameters: DeleteClassificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteClassificationResponse> {
        const response = await this.deleteClassificationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listClassifications without sending the request
     */
    async listClassificationsRequestOpts(requestParameters: ListClassificationsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["App-Token"] = await this.configuration.apiKey("App-Token"); // AppToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["App-Id"] = await this.configuration.apiKey("App-Id"); // AppId authentication
        }


        let urlPath = `/api/v1/client/classifications`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves a paginated list of all classifications available to the authenticated client. Each classification object includes a name, description, and timestamps for creation and modification. This endpoint is typically used to populate dropdowns or filters when creating or updating teams.
     * Get all classifications
     */
    async listClassificationsRaw(requestParameters: ListClassificationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListClassificationsResponse>> {
        const requestOptions = await this.listClassificationsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListClassificationsResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves a paginated list of all classifications available to the authenticated client. Each classification object includes a name, description, and timestamps for creation and modification. This endpoint is typically used to populate dropdowns or filters when creating or updating teams.
     * Get all classifications
     */
    async listClassifications(requestParameters: ListClassificationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListClassificationsResponse> {
        const response = await this.listClassificationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateClassification without sending the request
     */
    async updateClassificationRequestOpts(requestParameters: UpdateClassificationOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateClassification().'
            );
        }

        if (requestParameters['updateClassificationRequest'] == null) {
            throw new runtime.RequiredError(
                'updateClassificationRequest',
                'Required parameter "updateClassificationRequest" was null or undefined when calling updateClassification().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["App-Token"] = await this.configuration.apiKey("App-Token"); // AppToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["App-Id"] = await this.configuration.apiKey("App-Id"); // AppId authentication
        }


        let urlPath = `/api/v1/client/classifications/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateClassificationRequestToJSON(requestParameters['updateClassificationRequest']),
        };
    }

    /**
     * Updates an existing classification identified by its unique id. This endpoint allows modification of the classification’s name or description.
     * Update a classification
     */
    async updateClassificationRaw(requestParameters: UpdateClassificationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateClassificationResponse>> {
        const requestOptions = await this.updateClassificationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateClassificationResponseFromJSON(jsonValue));
    }

    /**
     * Updates an existing classification identified by its unique id. This endpoint allows modification of the classification’s name or description.
     * Update a classification
     */
    async updateClassification(requestParameters: UpdateClassificationOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateClassificationResponse> {
        const response = await this.updateClassificationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
