/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.tactixai.victorycode.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tactixai.victorycode.sdk.models.CompleteMultipartUploadDto
import com.tactixai.victorycode.sdk.models.CompletedPartDto

class CompleteMultipartUploadDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CompleteMultipartUploadDto
        //val modelInstance = CompleteMultipartUploadDto()

        // to test the property `uploadId`
        should("test uploadId") {
            // uncomment below to test the property
            //modelInstance.uploadId shouldBe ("TODO")
        }

        // to test the property `parts`
        should("test parts") {
            // uncomment below to test the property
            //modelInstance.parts shouldBe ("TODO")
        }

    }
}
