/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package com.tactixai.victorycode.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.tactixai.victorycode.sdk.models.ScoringPlayPlayerInvolvedDto

class ScoringPlayPlayerInvolvedDtoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ScoringPlayPlayerInvolvedDto
        //val modelInstance = ScoringPlayPlayerInvolvedDto()

        // to test the property `teamId`
        should("test teamId") {
            // uncomment below to test the property
            //modelInstance.teamId shouldBe ("TODO")
        }

        // to test the property `playerId`
        should("test playerId") {
            // uncomment below to test the property
            //modelInstance.playerId shouldBe ("TODO")
        }

        // to test the property `playerJerseyNumber`
        should("test playerJerseyNumber") {
            // uncomment below to test the property
            //modelInstance.playerJerseyNumber shouldBe ("TODO")
        }

        // to test the property `role`
        should("test role") {
            // uncomment below to test the property
            //modelInstance.role shouldBe ("TODO")
        }

    }
}
