/*
 * Victory Code Client API
 * This collection provides the core set of APIs for Tactix clients to interact with the platform. It covers authentication and token management, as well as a wide range of game-related endpoints including uploading full games, fetching generated clips, checking clipping status, retrieving game scoring summaries, and accessing detailed team statistics. All requests are versioned to ensure backward compatibility and smooth upgrades.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.victorycode.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.victorycode.sdk.JSON;

/**
 * CreateTeamResponseData
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class CreateTeamResponseData {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_SHORT_NAME = "shortName";
  @SerializedName(SERIALIZED_NAME_SHORT_NAME)
  @javax.annotation.Nullable
  private String shortName;

  public static final String SERIALIZED_NAME_SPORT = "sport";
  @SerializedName(SERIALIZED_NAME_SPORT)
  @javax.annotation.Nullable
  private String sport;

  public static final String SERIALIZED_NAME_COACH = "coach";
  @SerializedName(SERIALIZED_NAME_COACH)
  @javax.annotation.Nullable
  private Object coach = null;

  public static final String SERIALIZED_NAME_TEAM_LOGO = "teamLogo";
  @SerializedName(SERIALIZED_NAME_TEAM_LOGO)
  @javax.annotation.Nullable
  private String teamLogo;

  public static final String SERIALIZED_NAME_MASCOTS = "mascots";
  @SerializedName(SERIALIZED_NAME_MASCOTS)
  @javax.annotation.Nullable
  private List<String> mascots = new ArrayList<>();

  public static final String SERIALIZED_NAME_CLASSIFICATION = "classification";
  @SerializedName(SERIALIZED_NAME_CLASSIFICATION)
  @javax.annotation.Nullable
  private String classification;

  public static final String SERIALIZED_NAME_ID = "_id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String SERIALIZED_NAME_V = "__v";
  @SerializedName(SERIALIZED_NAME_V)
  @javax.annotation.Nullable
  private Integer v;

  public CreateTeamResponseData() {
  }

  public CreateTeamResponseData name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public CreateTeamResponseData shortName(@javax.annotation.Nullable String shortName) {
    this.shortName = shortName;
    return this;
  }

  /**
   * Get shortName
   * @return shortName
   */
  @javax.annotation.Nullable
  public String getShortName() {
    return shortName;
  }

  public void setShortName(@javax.annotation.Nullable String shortName) {
    this.shortName = shortName;
  }


  public CreateTeamResponseData sport(@javax.annotation.Nullable String sport) {
    this.sport = sport;
    return this;
  }

  /**
   * Get sport
   * @return sport
   */
  @javax.annotation.Nullable
  public String getSport() {
    return sport;
  }

  public void setSport(@javax.annotation.Nullable String sport) {
    this.sport = sport;
  }


  public CreateTeamResponseData coach(@javax.annotation.Nullable Object coach) {
    this.coach = coach;
    return this;
  }

  /**
   * Get coach
   * @return coach
   */
  @javax.annotation.Nullable
  public Object getCoach() {
    return coach;
  }

  public void setCoach(@javax.annotation.Nullable Object coach) {
    this.coach = coach;
  }


  public CreateTeamResponseData teamLogo(@javax.annotation.Nullable String teamLogo) {
    this.teamLogo = teamLogo;
    return this;
  }

  /**
   * Get teamLogo
   * @return teamLogo
   */
  @javax.annotation.Nullable
  public String getTeamLogo() {
    return teamLogo;
  }

  public void setTeamLogo(@javax.annotation.Nullable String teamLogo) {
    this.teamLogo = teamLogo;
  }


  public CreateTeamResponseData mascots(@javax.annotation.Nullable List<String> mascots) {
    this.mascots = mascots;
    return this;
  }

  public CreateTeamResponseData addMascotsItem(String mascotsItem) {
    if (this.mascots == null) {
      this.mascots = new ArrayList<>();
    }
    this.mascots.add(mascotsItem);
    return this;
  }

  /**
   * Get mascots
   * @return mascots
   */
  @javax.annotation.Nullable
  public List<String> getMascots() {
    return mascots;
  }

  public void setMascots(@javax.annotation.Nullable List<String> mascots) {
    this.mascots = mascots;
  }


  public CreateTeamResponseData classification(@javax.annotation.Nullable String classification) {
    this.classification = classification;
    return this;
  }

  /**
   * Get classification
   * @return classification
   */
  @javax.annotation.Nullable
  public String getClassification() {
    return classification;
  }

  public void setClassification(@javax.annotation.Nullable String classification) {
    this.classification = classification;
  }


  public CreateTeamResponseData id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public CreateTeamResponseData createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public CreateTeamResponseData updatedAt(@javax.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(@javax.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public CreateTeamResponseData v(@javax.annotation.Nullable Integer v) {
    this.v = v;
    return this;
  }

  /**
   * Get v
   * @return v
   */
  @javax.annotation.Nullable
  public Integer getV() {
    return v;
  }

  public void setV(@javax.annotation.Nullable Integer v) {
    this.v = v;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateTeamResponseData createTeamResponseData = (CreateTeamResponseData) o;
    return Objects.equals(this.name, createTeamResponseData.name) &&
        Objects.equals(this.shortName, createTeamResponseData.shortName) &&
        Objects.equals(this.sport, createTeamResponseData.sport) &&
        Objects.equals(this.coach, createTeamResponseData.coach) &&
        Objects.equals(this.teamLogo, createTeamResponseData.teamLogo) &&
        Objects.equals(this.mascots, createTeamResponseData.mascots) &&
        Objects.equals(this.classification, createTeamResponseData.classification) &&
        Objects.equals(this.id, createTeamResponseData.id) &&
        Objects.equals(this.createdAt, createTeamResponseData.createdAt) &&
        Objects.equals(this.updatedAt, createTeamResponseData.updatedAt) &&
        Objects.equals(this.v, createTeamResponseData.v);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, shortName, sport, coach, teamLogo, mascots, classification, id, createdAt, updatedAt, v);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateTeamResponseData {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    shortName: ").append(toIndentedString(shortName)).append("\n");
    sb.append("    sport: ").append(toIndentedString(sport)).append("\n");
    sb.append("    coach: ").append(toIndentedString(coach)).append("\n");
    sb.append("    teamLogo: ").append(toIndentedString(teamLogo)).append("\n");
    sb.append("    mascots: ").append(toIndentedString(mascots)).append("\n");
    sb.append("    classification: ").append(toIndentedString(classification)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    v: ").append(toIndentedString(v)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("name", "shortName", "sport", "coach", "teamLogo", "mascots", "classification", "_id", "createdAt", "updatedAt", "__v"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateTeamResponseData
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateTeamResponseData.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CreateTeamResponseData is not found in the empty JSON string", CreateTeamResponseData.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateTeamResponseData.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CreateTeamResponseData` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("shortName") != null && !jsonObj.get("shortName").isJsonNull()) && !jsonObj.get("shortName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `shortName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("shortName").toString()));
      }
      if ((jsonObj.get("sport") != null && !jsonObj.get("sport").isJsonNull()) && !jsonObj.get("sport").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `sport` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sport").toString()));
      }
      if ((jsonObj.get("teamLogo") != null && !jsonObj.get("teamLogo").isJsonNull()) && !jsonObj.get("teamLogo").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `teamLogo` to be a primitive type in the JSON string but got `%s`", jsonObj.get("teamLogo").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("mascots") != null && !jsonObj.get("mascots").isJsonNull() && !jsonObj.get("mascots").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `mascots` to be an array in the JSON string but got `%s`", jsonObj.get("mascots").toString()));
      }
      if ((jsonObj.get("classification") != null && !jsonObj.get("classification").isJsonNull()) && !jsonObj.get("classification").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `classification` to be a primitive type in the JSON string but got `%s`", jsonObj.get("classification").toString()));
      }
      if ((jsonObj.get("_id") != null && !jsonObj.get("_id").isJsonNull()) && !jsonObj.get("_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateTeamResponseData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateTeamResponseData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateTeamResponseData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateTeamResponseData.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateTeamResponseData>() {
           @Override
           public void write(JsonWriter out, CreateTeamResponseData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateTeamResponseData read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateTeamResponseData given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateTeamResponseData
   * @throws IOException if the JSON string is invalid with respect to CreateTeamResponseData
   */
  public static CreateTeamResponseData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateTeamResponseData.class);
  }

  /**
   * Convert an instance of CreateTeamResponseData to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

