/*
 * Victory Code Client API
 * Client APIs for Tactix partners: authenticate, upload game video, and retrieve games, plays, game recaps and team metadata.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tactixai.victorycode.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.tactixai.victorycode.sdk.model.DefenseStatsDto;
import com.tactixai.victorycode.sdk.model.DefenseTotalsDto;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.tactixai.victorycode.sdk.JSON;

/**
 * DefenseSectionDto
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class DefenseSectionDto {
  public static final String SERIALIZED_NAME_PLAYERS = "players";
  @SerializedName(SERIALIZED_NAME_PLAYERS)
  @javax.annotation.Nonnull
  private List<DefenseStatsDto> players = new ArrayList<>();

  public static final String SERIALIZED_NAME_TOTALS = "totals";
  @SerializedName(SERIALIZED_NAME_TOTALS)
  @javax.annotation.Nonnull
  private DefenseTotalsDto totals;

  public DefenseSectionDto() {
  }

  public DefenseSectionDto players(@javax.annotation.Nonnull List<DefenseStatsDto> players) {
    this.players = players;
    return this;
  }

  public DefenseSectionDto addPlayersItem(DefenseStatsDto playersItem) {
    if (this.players == null) {
      this.players = new ArrayList<>();
    }
    this.players.add(playersItem);
    return this;
  }

  /**
   * Get players
   * @return players
   */
  @javax.annotation.Nonnull
  public List<DefenseStatsDto> getPlayers() {
    return players;
  }

  public void setPlayers(@javax.annotation.Nonnull List<DefenseStatsDto> players) {
    this.players = players;
  }


  public DefenseSectionDto totals(@javax.annotation.Nonnull DefenseTotalsDto totals) {
    this.totals = totals;
    return this;
  }

  /**
   * Get totals
   * @return totals
   */
  @javax.annotation.Nonnull
  public DefenseTotalsDto getTotals() {
    return totals;
  }

  public void setTotals(@javax.annotation.Nonnull DefenseTotalsDto totals) {
    this.totals = totals;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DefenseSectionDto defenseSectionDto = (DefenseSectionDto) o;
    return Objects.equals(this.players, defenseSectionDto.players) &&
        Objects.equals(this.totals, defenseSectionDto.totals);
  }

  @Override
  public int hashCode() {
    return Objects.hash(players, totals);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DefenseSectionDto {\n");
    sb.append("    players: ").append(toIndentedString(players)).append("\n");
    sb.append("    totals: ").append(toIndentedString(totals)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("players", "totals"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("players", "totals"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DefenseSectionDto
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DefenseSectionDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in DefenseSectionDto is not found in the empty JSON string", DefenseSectionDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DefenseSectionDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `DefenseSectionDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DefenseSectionDto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("players") != null) {
        if (!jsonObj.get("players").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `players` to be an array in the JSON string but got `%s`", jsonObj.get("players").toString()));
        }
        JsonArray jsonArrayplayers = jsonObj.getAsJsonArray("players");
        // validate the required field `players` (array)
        for (int i = 0; i < jsonArrayplayers.size(); i++) {
          DefenseStatsDto.validateJsonElement(jsonArrayplayers.get(i));
        }
      }
      // validate the required field `totals`
      DefenseTotalsDto.validateJsonElement(jsonObj.get("totals"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DefenseSectionDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DefenseSectionDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DefenseSectionDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DefenseSectionDto.class));

       return (TypeAdapter<T>) new TypeAdapter<DefenseSectionDto>() {
           @Override
           public void write(JsonWriter out, DefenseSectionDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DefenseSectionDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DefenseSectionDto given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DefenseSectionDto
   * @throws IOException if the JSON string is invalid with respect to DefenseSectionDto
   */
  public static DefenseSectionDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DefenseSectionDto.class);
  }

  /**
   * Convert an instance of DefenseSectionDto to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

